### ISSUE TITLE
Konfiguration unter fhem/FHEM ablegen

### ISSUE THREAD

**Issue by jowiemann** [jemu75/fhemApp#10]
In der Basis cfg einen Verweis auf /fhem/FHEM möglich machen.

  "connection": {
    "location": "http://fhem",
    "port": "8083",
    "path": "fhem",
    "usrcfg": "/FHEM/fhemapp.cfg"
  },

Die cfg ist so über das Fhem Web Frontend editierbar.

**Comment by jemu75** [comment]
umgesetzt mit Version 4 :)
