### ISSUE TITLE
Ebenen-Sichtbarkeit in der Vorlagenbearbeitung

### ISSUE THREAD

**Issue by benni1972** [jemu75/fhemApp#100]
Hallo Jens,

ich habe eine Vorlage, die 2 Ebenen hat. Je nach einem Attribut-Wert am zugewiesenen Device wird die eine Ebene eingeblendet und die andere aus, oder umgekehrt.

Das ganze funktioniert in der normalen Ansicht, wie erwartet. Allerdings wird, wenn ich in der Vorlagenbearbeitung bin und dort das device wechsle, die Sichtbarkeit der Ebenen nicht umgeschaltet. Für mich sieht es so aus, als ob hier grundsätzlich die erste Ebene einfach angezeigt wird. Wenn ich mir dort statt des Panels, das JSON mit den aktuellen Werten anzeige lassen, stimmt auch alles.

Wie gesagt, ist nur die Ansicht in der Vorlagenbearbeitung betroffen. Sonst passt es! Hat also keine besonder Prio!

Gruß Benni

**Comment by jemu75** [comment]
mit v4.3.0 gelöst
