### ISSUE TITLE
Suchergebnisse bei der Device-Zuordnung im Panel verfielfachen sich mit der Zeit

### ISSUE THREAD

**Issue by benni1972** [jemu75/fhemApp#101]
Hallo Jens,

ich habe hier so ein ähnliches Phänomen, wie Sebastian neulich bei den Menüs.

Ich bin gerade dabei, meine Fenster, nach und nach dem entsprechenden Template zuzuordnen und stelle fest, dass sich mit der Zeit die Suchergebnisse vervielfachen. Leider konnte ich noch kein Muster ausfindig machen.

Hier noch ein Screenshot:

<img width="770" alt="Bildschirm­foto 2024-05-04 um 20 28 41" src="https://github.com/jemu75/fhemApp/assets/82200777/22f8f91a-2373-448f-8464-625966d1554c">

Gruß Benni

**Comment by Himbi777** [comment]
Hi zusammen 
Das habe ich auch festgestellt und auch das Muster erkannt.
Wenn man mehrere Panels hintereinander anlegt, wird bei der Gerätesuche jedes Mal das Ergebnis erhöht.
Erstes Panel - zwei gefundene Geräte 
Zweites Panel - vier gefundene Geräte 
Drittens Panel - sechs gefundene Geräte....

Gruss Gerhard

**Comment by benni1972** [comment]
Stimmt! Jetzt sehe ich es auch! Mit jedem neuen Panel tauchen sämtliche Geräte, entsprechend der erstellten Panels oft in den Suchergebnissen auf!
Da fehlt irgendwo ein clear vor dem re-fill ;)

**Comment by jemu75** [comment]
Fehler ist bestätigt. Wird mit v4.1.3 behoben

**Comment by jemu75** [comment]
behoben mit v4.1.3
