### ISSUE TITLE
%i - Funktion in der Version4

### ISSUE THREAD

**Issue by Himbi777** [jemu75/fhemApp#104]
Hallo Jens

bei der Umsetzung meiner Panels bin ich nun an dem Punkt der i%-Variable:
Bei der Version 3  konnte der Dimmer z.B mit einem Button-Click um 10-Punkte verkleinert werden:
`"bri:10:bri %i-10","bri::off"`
Wie kann dies in der V4 umgesetzt werden ?  Die Inkrementierung mit i% ist nicht in der Erläuterung enthalten.
Danke vorab für deinen tollen Support.

Gruß Gerhard

**Comment by jemu75** [comment]
Hallo Gerhard,

in Version 4 ist diese Möglichkeit in `%d(<decimals>, <offset>)` integriert.
Den offset-Wert kannst du optional verwenden um den Wert des Readings nach oben bzw. nach unten zu verändern.
In der Dokumentation sind auch ein paar Beispiele dazu hinterlegt.

Melde Dich gern, wenn Du weitere Fragen hast.

Grüße
Jens

**Comment by Himbi777** [comment]
Hallo Jens
Danke, gab's gefunden im Template Thermostat 👍

Gruss und noch einen schönen Sonntag
