### ISSUE TITLE
FHEMApp sendet Device-Name mit großem Anfangsbuchstaben, kleiner angegeben

### ISSUE THREAD

**Issue by marvin78** [jemu75/fhemApp#109]
FHEMAPP sendet bei einem meiner Dummys, den ich zur Codeeingabe bei der Alarmanlage missbrauche mit großem Anfangsbuchstaben. Das Device wird aber klein geschrieben. Folgender Screenshot zeigt, was ich meine:

![2024-05-23 09_55_35-FHEMApp v4](https://github.com/jemu75/fhemApp/assets/10920356/b9fe4e4b-b86f-492b-a744-415f03625ec8)

**Comment by jemu75** [comment]
Schicke  bitte mal die Panel- bzw. Templatedefinition.

**Comment by marvin78** [comment]
`{
	"name": "Alarm Keypad",
	"template": null,
	"panel": {
		"devices": [
			"keypad:alarmSequenceDummy",
			"alarm:Alarm"
		],
		"navigation": [
			"::alarm"
		],
		"show": [
			"alarm-state:on:true",
			"alarm-state:standby:true",
			"alarm-state:armin:true",
			"alarm-state:alarm:true",
			"alarm-state:triggered:true",
			"::false"
		],
		"expandable": [
			"::false:true"
		],
		"sortby": [
			"::A001"
		]
	},
	"status": {
		"title": [
			"Keypad"
		]
	},
	"main": [
		{
			"level": {
				"left1": "btn",
				"mid": "btn",
				"right2": "btn"
			},
			"left1": {
				"btn": [
					"::mdi-numeric-7-box:::outlined"
				],
				"click": [
					"::set keypad 7"
				]
			},
			"mid": {
				"btn": [
					"::mdi-numeric-8-box:::outlined"
				],
				"click": [
					"::set keypad 8"
				]
			},
			"right2": {
				"btn": [
					"::mdi-numeric-9-box:::outlined"
				],
				"click": [
					"::set keypad 9"
				]
			}
		},
		{
			"level": {
				"left1": "btn",
				"mid": "btn",
				"right2": "btn"
			},
			"left1": {
				"btn": [
					"::mdi-numeric-4-box:::outlined"
				],
				"click": [
					"::set keypad 4"
				]
			},
			"mid": {
				"btn": [
					"::mdi-numeric-5-box:::outlined"
				],
				"click": [
					"::set keypad 5"
				]
			},
			"right2": {
				"btn": [
					"::mdi-numeric-6-box:::outlined"
				],
				"click": [
					"::set keypad 6"
				]
			}
		},
		{
			"level": {
				"left1": "btn",
				"mid": "btn",
				"right2": "btn"
			},
			"left1": {
				"btn": [
					"::mdi-numeric-1-box:::outlined"
				],
				"click": [
					"::set keypad 1"
				]
			},
			"mid": {
				"btn": [
					"::mdi-numeric-2-box:::outlined"
				],
				"click": [
					"::set keypad 2"
				]
			},
			"right2": {
				"btn": [
					"::mdi-numeric-3-box:::outlined"
				],
				"click": [
					"::set keypad 3"
				]
			}
		},
		{
			"level": {
				"left1": "btn",
				"mid": "btn",
				"right2": "btn"
			},
			"left1": {
				"btn": [
					"::mdi-lock-reset:::outlined"
				],
				"click": [
					"::set keypad reset"
				]
			},
			"mid": {
				"btn": [
					"::mdi-numeric-0-box:::outlined"
				],
				"click": [
					"::set keypad 0"
				]
			},
			"right2": {
				"btn": [
					"::mdi-location-enter:::outlined"
				],
				"click": [
					"::set keypad enter"
				]
			}
		}
	],
	"info": {}
}`

**Comment by marvin78** [comment]
```
{
	"name": "Alarm Keypad",
	"template": null,
	"panel": {
		"devices": [
			"keypad:alarmSequenceDummy",
			"alarm:Alarm"
		],
		"navigation": [
			"::alarm"
		],
		"show": [
			"alarm-state:on:true",
			"alarm-state:standby:true",
			"alarm-state:armin:true",
			"alarm-state:alarm:true",
			"alarm-state:triggered:true",
			"::false"
		],
		"expandable": [
			"::false:true"
		],
		"sortby": [
			"::A001"
		]
	},
	"status": {
		"title": [
			"Keypad"
		]
	},
	"main": [
		{
			"level": {
				"left1": "btn",
				"mid": "btn",
				"right2": "btn"
			},
			"left1": {
				"btn": [
					"::mdi-numeric-7-box:::outlined"
				],
				"click": [
					"::set keypad 7"
				]
			},
			"mid": {
				"btn": [
					"::mdi-numeric-8-box:::outlined"
				],
				"click": [
					"::set keypad 8"
				]
			},
			"right2": {
				"btn": [
					"::mdi-numeric-9-box:::outlined"
				],
				"click": [
					"::set keypad 9"
				]
			}
		},
		{
			"level": {
				"left1": "btn",
				"mid": "btn",
				"right2": "btn"
			},
			"left1": {
				"btn": [
					"::mdi-numeric-4-box:::outlined"
				],
				"click": [
					"::set keypad 4"
				]
			},
			"mid": {
				"btn": [
					"::mdi-numeric-5-box:::outlined"
				],
				"click": [
					"::set keypad 5"
				]
			},
			"right2": {
				"btn": [
					"::mdi-numeric-6-box:::outlined"
				],
				"click": [
					"::set keypad 6"
				]
			}
		},
		{
			"level": {
				"left1": "btn",
				"mid": "btn",
				"right2": "btn"
			},
			"left1": {
				"btn": [
					"::mdi-numeric-1-box:::outlined"
				],
				"click": [
					"::set keypad 1"
				]
			},
			"mid": {
				"btn": [
					"::mdi-numeric-2-box:::outlined"
				],
				"click": [
					"::set keypad 2"
				]
			},
			"right2": {
				"btn": [
					"::mdi-numeric-3-box:::outlined"
				],
				"click": [
					"::set keypad 3"
				]
			}
		},
		{
			"level": {
				"left1": "btn",
				"mid": "btn",
				"right2": "btn"
			},
			"left1": {
				"btn": [
					"::mdi-lock-reset:::outlined"
				],
				"click": [
					"::set keypad reset"
				]
			},
			"mid": {
				"btn": [
					"::mdi-numeric-0-box:::outlined"
				],
				"click": [
					"::set keypad 0"
				]
			},
			"right2": {
				"btn": [
					"::mdi-location-enter:::outlined"
				],
				"click": [
					"::set keypad enter"
				]
			}
		}
	],
	"info": {}
}
```

**Comment by jemu75** [comment]
Danke für die Paneldefinition. Hier handelt es sich um einen Fehler. 

Als Workaround schlage ich vor, dass du für das zweite definierte Device einen anderen Key anstatt `alarm` verwendest. 

Hintergrund: aktuell wird in deiner Paneldefinition `keypad` durch `alarmSequenceDummy` und danach `alarm` durch `Alarm` ersetzt. Damit wird `alarmSequenceDummy` zu `AlarmSequenceDummy`

**Comment by marvin78** [comment]
Ok. Danke. Ich habe mir damit geholfen, den Numen des Dummys anzupassen.

**Comment by jemu75** [comment]
gelöst mit v4.2.0
