### ISSUE TITLE
LED RGB Template

### ISSUE THREAD

**Issue by jowiemann** [jemu75/fhemApp#11]
Erweitern der CFG für LED RGB Teemplates.

**Comment by Himbi777** [comment]
Ich bin gerade dabei mir ein vereinfachtes Template für einen RGB-Stripe zusammen zu bauen.
Ist es möglich, die Farbe der Bar mit der aktuellen RGB-Farbe des Stripes zu belegen?
Wenn ich 'success' mit z.B '#FF0000' ersetze ,klappt die Änderung der Farbe.

Danke vorab, für entsprechende Tipps

**Comment by jemu75** [comment]
Hallo, man könnte es über eine "Ersetzung" realisieren, wenn es in FHEM ein reading gäbe, dass den Farbwert zurück gibt. Dann könnte man das "Level" der Bar aber nicht mehr parallel zur Farbe verändern.

**Comment by Himbi777** [comment]
Hallo jemu75
Das habe ich hin bekommen mit dem #FF900F z.B.
Ich wollte für den RGB- Stripe zum einen den Dimmwert als "Level" und die Farbe mit der aktuellen LED-Farbe darstellen.
 meine Idee war:
  "bar": ["state:off:0:success","pct::%n:color %s"],
wenn , wie im Beispiel, das Reading color existiert, wird der Farbwert entsprechend us diesem Reading übernommen.
Wär schön, wenn es so klappen könnte.

Gruss Gerhard

**Comment by jemu75** [comment]
Hallo Gerhard,

technisch machbar wäre der Wunsch. Allerdings ist das mit einem erheblichen Umbau der bisherigen Logik verbunden. Zudem baue ich in nächster Zeit einen Colorpicker ein, mit dem sich die LED Devices besser steuern lassen. Letztlich ist FHEMapp primär auf die Darstellung ausgerichtet. Alles was Logik betrifft, soll weitgehend in FHEM abgebildet werden, da es hier sehr umfangreiche Möglichkeiten gibt. 
Ich werde den Vorschlag deshalb nicht weiter verfolgen.

**Comment by Himbi777** [comment]
Hallo Jens
Der Colorpicker ist ausreichend,  danke für deine Unterstützung

**Comment by Mockabear** [comment]
> Zudem baue ich in nächster Zeit einen Colorpicker ein, mit dem sich die LED Devices besser steuern lassen.

Wo finde ich den denn Colorpicker oder ein Beispiel?

**Comment by jemu75** [comment]
Der Colorpicker ist in Version 3 nicht verfügbar. Ich werde künftig einen Colorpicker zur Verfügung stellen. Termin dafür steht aber leider noch nicht.
