### ISSUE TITLE
Navigationspunkte sortieren

### ISSUE THREAD

**Issue by marvin78** [jemu75/fhemApp#112]
In der Hilfe steht, dass man die Reihenfolge der Navigationspunkte festlegen kann. Ich habe keine Möglichkeit gefunden, die Punkte zu sortieren. Wie lassen sich die Punkte sortieren?

**Comment by Himbi777** [comment]
Hallo Marvin 
Das geht nur mit der entsprechenden Chechbox.
![Screenshot_20240529-181918~2](https://github.com/jemu75/fhemApp/assets/59026971/73de8131-fd78-4e1c-ab54-a65e3f16b66b)

Damit sind die Unterpunkte im entsprechenden Bereich alphabetisch sortiert, ist der Haken nicht gesetzt, sind sie in der Reihenfolge wie sie angelegt worden sind.

Gruss Gerhard

**Comment by marvin78** [comment]
Hm. Danke. Dann muss man, um die Reihenfolge zu ändern, Punkte mühsam austauschen. 

Gäbe es die Möglichkeit, hier eine Drag&Drop Sortierung einzubauen? Man entwickelt ja so eine Oberfläche nach und nach und so entwickeln sich die Menüpunkte nach und nach und am Ende ist die alphabetische Sortierung falsch und die, in der die Navigationspunkte entstanden sind, auch.

**Comment by jemu75** [comment]
Hallo @marvin78,

wie @Himbi777 bereits richtig geschrieben hat, gibt es zwei Möglichkeiten in den Einstellungen unter dem Tab Navigation, die Reihenfolge der Navigationspunkte anzupassen. Entweder über die Reihenfolge der definierten Navigationspunkte oder untergeordnete Navigationspunkte alphabetisch aufsteigend über den "sortiert" Button. 

Dein Vorschlag die Navigationspunkte via Drag&Drop zu sortieren finde ich sehr gut und würde den mit umsetzen. Ich gebe nochmal Bescheid, wenn der Zeitpunkt konkret wird.

**Comment by jemu75** [comment]
Sortierung mit v4.3.0 gelöst
