### ISSUE TITLE
Basic auth

### ISSUE THREAD

**Issue by marvin78** [jemu75/fhemApp#115]
Kann es sein, dass BasicAuth in image und/oder iframe nicht funktioniert?

Versucht man ein Auth mit bspw. folgender URL (escaped):

https\\://user\\:password@doorcam.meinedomain.com/video4.mjpg

erhält mein auf der Konsole: Blocked by Client. 

Die URL funktioniert einwandfrei im Browser und auch ohne User/Passwort funktioniert die URL in FHEMApp (dann mit Eingabe des Users und Passworts über eine Tastatureingabe).

**Comment by jemu75** [comment]
Ich habe dazu mal etwas recherchiert. Soweit ich das aktuell sagen kann, unterstützt der `src` Parameter von *img* bzw. *iframe* diese Authentifizierung nicht.

**Comment by marvin78** [comment]
Hm. Dann muss ich mal sehen, wie ich den Reverse-Proxy dafür missbrauchen kann.

**Comment by marvin78** [comment]
Also über NPM lässt sich das leicht lösen. Ich schließe das hier.
