### ISSUE TITLE
imageUrl Definition fehlt in GUI+RAW obwohl in der config.json enthalten

### ISSUE THREAD

**Issue by binford6000** [jemu75/fhemApp#117]
Gegeben ist ein Template "FHEMApp_V4" mit konfigurierter imagURL:
![SCR-20240710-bye](https://github.com/jemu75/fhemApp/assets/29679540/ab557f2c-8731-4422-8f63-f38f029d2e43)

Allerdings ist in der GUI (und in RAW) nichts davon zu sehen / zu ändern (siehe Bild oben)

In der config.json ist es natürlich enthalten (sonst würde es ja auch nicht dargestellt werden):
![SCR-20240710-c54](https://github.com/jemu75/fhemApp/assets/29679540/8124a3b3-62ce-4f82-80a6-8b386e3ebd0a)

Den nicht vorhandenen Titel wird dagegen korrekt mit rotem ! angezeigt.

Ich habe verschiedene Browser ausprobiert - sieht überall gleich aus.

**Comment by jemu75** [comment]
Ich konnte das bei mir bisher leider nicht reproduzieren. Kannst du mir bitte mal die Template-Definition (json) schicken, damit ich das mit deinem Template testen kann.

**Comment by binford6000** [comment]
[fhemapp_template.json](https://github.com/user-attachments/files/16258349/fhemapp_template.json)

**Comment by jemu75** [comment]
Ich habe mir das Template angesehen. In dem Template ist unter "Status" tatsächlich keine Image-URL hinterlegt. Zudem irritiert mich auch, dass in deinem Screenshot "config.json" auch eine Definition für den Parameter "sortby" zu sehen ist. Auch dieser ist in deinem Template nicht definiert.

Ich würde im Moment vermuten, dass du die Image-URL und auch sortby im zugehörigen Panel und nicht im Template definiert hast. Das kann ich aber nur prüfen, wenn ich auch die zugehörige Panel-Definition hätte. Vielleicht kannst du mir ja auch diese noch zukommen lassen, damit ich das Problem weiter untersuchen kann.

**Comment by binford6000** [comment]
> Ich würde im Moment vermuten, dass du die Image-URL und auch sortby im zugehörigen Panel und nicht im Template definiert hast

Natürlich, was sonst...
Notiz an mich: Entweder nur mit Template oder nur Panel. Aber nicht mischen...
