### ISSUE TITLE
mdi Icons

### ISSUE THREAD

**Issue by jowiemann** [jemu75/fhemApp#12]
Tabelle, der zur Verfügung stehenden Icons

**Comment by jemu75** [comment]
siehe: [Material Design Icons](https://materialdesignicons.com/)

**Comment by Himbi777** [comment]
Warum klappt z.B das folgende Icon nicht :
 **mdi-lightbulb-on-40**
ich wollte damit den aktuellen Dimmerstaus darstellen.
Gruß und danke vorab.
Gerhard
