### ISSUE TITLE
Favicon under iOS 18 is always bright

### ISSUE THREAD

**Issue by binford6000** [jemu75/fhemApp#122]
Since the latest update to iOS 18 the favicon is displayed always in bright color.
With iOS 17.x it was displayed in its original colors (black).

I *think* with iOS 18 it needs two versions to change between bright and dark mode
since Apple introduced some changes in App icons and maybe also in favicon icons.

![24-09-20 14-25-52 4728](https://github.com/user-attachments/assets/c49f2ba2-9d02-4ddf-b112-bd8e9ad8c82c)

Older iPadOS for example still shows the original Favicon:

![image](https://github.com/user-attachments/assets/075616dc-8175-49d9-b4ae-d9806ed5b1e2)

**Comment by jemu75** [comment]
The use of a transparent background is recommended for favicons. I use a transparent background for the **FHEMApp** favicon. At the moment I have no idea how I can help here. If there are any solutions, please let me know so that I can improve the compatibility for **FHEMApp**.

**Comment by jemu75** [comment]
Issue closed, if problem still exists, please contact me again
