### ISSUE TITLE
Platzverschwendung: Panels sollten in den Spalten auffüllen (optional)

### ISSUE THREAD

**Issue by marvin78** [jemu75/fhemApp#128]
Ich stelle immer wieder fest, dass ich viel Platz in meinen Dashboards verschwende. Deshalb wäre es gut, wenn die Panels in der Horizontalen nicht alle nach unten wandern würden, wen ein Panel in einer anderen Spalte höher ist. Das würde eine Menge Platz sparen. Es würde ggf. auch etwas unaufgeräumter aussehen aber dem kann man mit etwas Spielen mit den Zeilenhöhen ggf. Abhilfe schaffen. 

Wäre es möglich, dass man optional die Panels in den Spalten direkt untereinander schieben kann?

Dabei sollte auch die Anordnung ggf. auf Spaltenebene funktionieren. Also Panel gehört in Spalte x und dann wirkt die Sortierung.

**Comment by jemu75** [comment]
Diesen Wunsch gibt es schon längere Zeit. (seit Version 3.x) Leider ist das in Verbindung mit dem Responsive Design nicht ganz einfach zu lösen, da die Panels je nach Displaybreite in den Spalten "wandern". D.h. ein Panel, was auf einem großen Desktopbildschirm in Spalte 4 angezeigt wird, wandert bei kleineren Displays in eine andere Spalte. Bishin zu Smartphone-Displays, bei einen nur noch eine Spalte verfügbar ist. 

Da das Thema nun erneut gewünscht wird, werde ich auf einem Ansatz, den ich dazu vor einiger Zeit schon hatte mal noch etwas rumdenken und mir was einfallen lassen.

**Comment by jemu75** [comment]
wird umgesetzt mit v.4.5.0

**Comment by jemu75** [comment]
umgesetzt mit v4.5.0

**Comment by marvin78** [comment]
Danke. Sehr schön!!

Aber es ist nun nicht optional oder?

**Comment by marvin78** [comment]
Nachtrag: Eigentlich müsste man nun noch die Möglichkeit haben, Panels auf Spalten aufzuteilen. Wenn ich zum Beispiel links oben ein großes Panes unterbringen möchte, dann müsste man die Möglichkeit haben, dass in der äußerst linken Spalte bspw. nur 3 Panels unterkommen, während es in Spalte 2 und 3 ggf. 4 oder 5 sind.  Wäre das möglich
