### ISSUE TITLE
Umstellung von light auf dark oder umgekehrt passiert erst nach reload

### ISSUE THREAD

**Issue by marvin78** [jemu75/fhemApp#129]
Siehe Titel. Die Umstellung funktioniert nicht durch den Trigger aus dem Websocket sondern nur nach Reload.

**Comment by jemu75** [comment]
Die Umstellung funktioniert automatisch und reagiert auf das definierte Reading. Kannst du mir deine Definition, die du in den App-Einstellungen unter `Allgemein -> Darkmode über FHEM` hinterlegt hast, bitte hier posten.

**Comment by marvin78** [comment]
`HM_LS_vorne-luminance:dark`

Und es funktioniert reproduzierbar nicht so, wie du beschreibst. Es schaltet zwar um, aber erst nach einem Reload der Seite. Ich erkenne das immer schnell daran, dass ich einige iframe Panels auch mit demselben Reading umschalten lasse (bei Grafana geht das über die URL). Die schalten auch tatsächlich sofort um und haben einen schwarzen Hintergrund, wenn darf true ist (oder eben umgekehrt). FHEMApp ist dann noch hell bzw. dunkel.

**Comment by jemu75** [comment]
Ich konnte das jetzt auch reproduzieren. Der Fehler wird mit behoben.

**Comment by jemu75** [comment]
mit v4.5.1 behoben
