### ISSUE TITLE
Option maximized für Panels

### ISSUE THREAD

**Issue by marvin78** [jemu75/fhemApp#130]
Es wäre gut, wenn man die Option maximized für ein Panel hätte und dann ggf. auch einstellen könnte, wie groß das Panel dann maximiert wird (Prozent vom Bildschirm o.ä.). Die Kirsche auf der Torte wäre dann, wenn man ein Panel, das maximiert ist auch schließen könnte,

Beispiel:

Ich blende innerhalb eines Info-Panels auf der Startseite für einige Sekunden das Bild einer Kamera ein, wenn jemand klingelt und oder an der Haustür vorbei geht. Das schiebt unter dem Panel alles nach unten, viel freier Raum entsteht und es sieht nicht schön aus. Schöner wäre es, wenn dann ein schon maximiertes Panel eingeblendet würde, dass das Bild der Kamera anzeigt und das man dann ggf. auch schließen kann, damit der dahinterliegende Content wieder sichtbar wird, das Panel dann aber nicht minimiert das Dashboard durcheinander macht, also dass es dann durch Userinteraktion wirklich ausgeblendet ist.

Es gibt sicher noch andere Beispiele, für die das sinnvoll wäre. :)

**Comment by jemu75** [comment]
Die Option "maximized" sorgt dafür, dass ein Panel den kompletten verfügbaren Platz erhält. Andere Panels werden in dem Moment generell nicht mehr angezeigt. Mit dem Umbau, des Panel-Grid hat sich das Verhalten ab Version 4.5.0 zudem geändert. Es entstehen nun keine Lücken mehr, wenn Panels unterschiedlich hoch sind.
Falls du noch was anderes meinst, dann bitte noch mal melden.

**Comment by marvin78** [comment]
Ich meine nicht maximizable sondern maximized. Das wäre eine neue Option, die ein Panel, sobald show true wird (bspw. eine Bewegung) maximiert darstellt und sonst eben garnicht (show=false). Damit das ganze dann auch praktikabel ist, müsste man das Panel dann aber auch manuell über die Pfeile rechts oben wieder ausblenden können (show=false). Daran wird es vermutlich scheitern.

**Comment by jemu75** [comment]
Ich werde mit Version 4.6 eine neue Funktion bereitstellen. 
Es wird einen Parameter "popout" unter den allgemeinen Einstellungen im Panel/Template geben.
Über diesen kann man steuern, wann ein Panel als "Popup" eingeblendet wird. Es wird hier auch die Möglichkeit geben, beim Schließen des "Popup" optional ein Kommando an FHEM zu senden. 
Ich denke diese Funktion ergänzt die bisherigen Funktionen (expand, maximized) am besten.

**Comment by marvin78** [comment]
Das übersteigt meine Erwartungen. Top!

**Comment by jemu75** [comment]
Feature mit Version 4.6.0 bereitgestellt

**Comment by marvin78** [comment]
Gibt es die Möglichkeit, dass die Popouts nur in einem Raum aufpoppen, also so, dass man eine Navigation angeben kann? Wenn das Kamerabild, das ins Dashboard gehört auch auf dem Handy der Frau im Raum Bad aufpoppt oder alle Popouts gar auch in den Einstellungen aufpoppen, ist das seltsam.

Auch habe ich nun einige Panels, die ich als Poppout anzeige, wenn ich einen Button länger drücke, um beispielsweise eine Dimmersteuerung zu vereinfachen. Dazu setze ich dann beim longclick ein Reading, was wiederum beim Panel das Popout auslöst. Das muss dann aber nicht auf jedem Tablet im Dashboard angezeigt werden, sondern nur in dem Fenster, in dem ich mich gerade befinde. Hier wären wir aber wieder an dem Punkt, dass man wissen muss, in welcher Navigation wir uns befinden. Das war ja schon an anderer Stelle problematisch. Deshalb wäre es in erster Instanz ganz gut, wenn man den Raum für das Popout angeben könnte und wenn es in den Einstellungen eben nicht angezeigt würde. Es fällt mir kein Grund ein, bei dem letzteres Sinn ergibt.  :)

**Comment by jemu75** [comment]
Der Ansatz für die Popup war folgender. Wenn in FHEM irgendwas passiert, was die Aufmerksamkeit des Benutzers erfordert, dann soll dies direkt angezeigt werden. Hierfür wird den betreffende Panel, egal unter welchen Navigationspunkt(en) es sich befindet, in den Vordergrund geholt. 
Also in der Praxis z.B. wenn ein Bewegungsmelder anschlägt, ein Fenster offen ist, ein Device irgendein Problem hat usw.

Wenn man die Funktion auf bestimmte Navigationspunkte einschränkt, dann ist der Zweck nicht mehr erfüllt.

Und damit erklärt sich, weshalb das auch zutrifft, wenn man gerade in den Einstellungen unterwegs ist.

Die Variante dass man mit einem Button ein reading setzt, welches dann wiederum ein Popup triggert, ist durchaus machbar, aber so wie oben beschrieben, nicht sinnvoll, da es ja überall angezeigt wird. 

Beim usecase mit der Kamera gibt es auch mehrere Ansätze. Wenn man in einem bestimmten Navigationspunkt ist, in dem ein Kamerabild angezeigt wird, dann kann man dieses bei Bedarf über maximize vergrößern. Wenn das Kamerabild in den Vordergrund kommen soll, sobald Bewegung erkannt wird, dann wäre popout das geeignete Mittel. 

Welche usecases wären deiner Ansicht nach mit den aktuellen Möglichkeiten nicht abbildbar?

**Comment by marvin78** [comment]
Naja.Wenn man die Möglichkeiten sieht, wachsen automatisch die Anforderungen ;)

Mein Usecase ist folgender:

Ich habe ein Panel im Dashboard, in dem alle eingeschalteten Leuchten angezeigt werden (also eine Zeile pro eingeschalteter Leuchte). Sind sie aus, werden sie ausgeblendet. Es gibt im Panel rechts einen Button zum Ausschalten der Leuchten. So sieht das aus:

![image](https://github.com/user-attachments/assets/90489db3-3668-4cc4-bd6e-fb6c271f48ee)

Mit den neuen Möglichkeiten des Popouts habe ich dann die Leuchten, die noch eine andere Bedienung, als an/aus zulassen, mit einem Longklick-Button ausgestattet (und den Button dann mit tonal gekennzeichnet). Klickt/Tippt man diesen Button kurz an, wird weiterhin ausgeschaltet (und ausgeblendet), klickt/tippt man ihn lang an, erscheint als Dialog das Panel mit der Steuerung (Dimmen, Farben und Co,). 

![image](https://github.com/user-attachments/assets/15358a1f-817a-4350-b0c8-ad9139c582b9)

Diese Steuerung muss natürlich eigentlich nur in dem Browserfenster angezeigt werden, in dem man sich gerade befindet und aus dem man steuern möchte. Andere Anwender wundern sich sonst, dass sie diesen Dialog bekommen, wenn sie gerade gleichzeitig rein schauen. 

Ich verstehe (das habe ich eigentlich auch schon vorher), dass das eigentlich ein anderer Anwendungsfall ist. Es ist kein Popout sondern ein Popup oder bessser Modal-Dialog. Aus meiner Sicht, wäre es toll, die Möglichkeit eines solchen Modals zu haben. An vielen Stellen könnte man damit die Übersicht erhöhen und die Möglichkeiten vervielfachen.

**Comment by jemu75** [comment]
Vielen Dank für die hilfreichen Infos. Ich denke das lässt sich lösen. Ich würde das allerdings über das Button Element realisieren. Über diesen kann man ja heute schon FHEM-Befehle senden, externe Links aufrufen oder in der App navigieren. Hier könnte ich eine weitere Option schaffen, um ein beliebiges Panel als popup (modal) aufzurufen. Damit sparst du auch das Reading, welches du bisher zum aktivieren des popout verwendest.
Was meinst du zu dem Ansatz?

**Comment by marvin78** [comment]
:) Danke. Das halte ich für prima!

**Comment by jemu75** [comment]
Lösung mit **v4.8.0** bereitgestellt. 

Ps.: bei weiteren Punkten zu dem Thema bitte ein neues Issue eröffnen
