### ISSUE TITLE
Vertikale Slider: Höhe anpassen

### ISSUE THREAD

**Issue by marvin78** [jemu75/fhemApp#131]
Bei vertikalen Slidern wäre es gut, wenn die Höhe der Ebene angepasst werden könnte (oder dann eben die Länge der Slider). Aktuell hat die Höheneinstellung der Ebene auf Ebenen mit Slidern keinen Einfluss. Die sind immer gleich lang (hoch).

**Comment by jemu75** [comment]
wird mit v4.5.0 behoben

**Comment by jemu75** [comment]
behoben mit v4.5.0

**Comment by marvin78** [comment]
Super. Danke.

**Comment by marvin78** [comment]
Kann es sein, dass das mit der letzten Version wieder kaputt gegangen ist? Meine Slider sind wieder riesig.

**Comment by jemu75** [comment]
Stimmt, aktuell reagiert der verticale Slider nicht mehr auf die Höhe der Ebene. Ich korrigiere das kurzfristig.

**Comment by jemu75** [comment]
Fehler korrigiert mit v4.6.1
