### ISSUE TITLE
Paneldarstellung teilweise kaputt

### ISSUE THREAD

**Issue by marvin78** [jemu75/fhemApp#135]
Seit dem Update, welches die Platzverschwendung beseitigt hat, habe ich auf einigen Seiten und auch nur auf dem Laptop (bisher habe ich es nur da gesehen) in Chrome folgende Darstellung:

![image](https://github.com/user-attachments/assets/aa4d35d1-da0d-4a26-b10f-d48d5da62390)
![image](https://github.com/user-attachments/assets/17caa586-23ce-472d-848a-51b938cc3f73)

Es gibt auf dieser speziellen Seite nur noch 2 bzw. weiter unten sogar nur noch eine Spalte. Andere Seiten in derselben Instanz sehen ganz normal aus und haben 3 Spalten. Es ist auch immer Platz genug für 3 Spalten und vor dem besagten Update wurden auch 3 Spalten dargestellt. Es gibt Seiten, bei denen ist die Darstellung wie erwartet (3 Spalten und in der vorgegebenen Sortierreihenfolge) und auf anderen ist es so, wie im Beispiel. Es gibt iframes auf den falsch dargestellten Seiten. Allerdings gibt es auch Seiten mit iframes, die korrekt dargestellt werden, deshalb kann ich kein echtes Muster erkennen. Auch auf dem Tablet wird alles dargestellt, wie erwartet.

**Comment by jemu75** [comment]
Ich konnte das Verhalten reproduzieren. Aufgetreten ist das auch bei mir auf Seiten, auf denen iframes bzw. charts angezeigt werden. Insbesondere wenn man die Fenstergröße des Browsers ändert, tritt der Effekt auf solchen Seiten auf. Wenn die Seite keine iframes und charts beinhaltet, dann habe ich das Problem nicht beobachtet.

Ich werde das Problem mit der nächsten Version beheben.

**Comment by jemu75** [comment]
Behoben mit v4.5.3
