### ISSUE TITLE
Different size of button- and info-element

### ISSUE THREAD

**Issue by binford6000** [jemu75/fhemApp#137]
Given a [template.json](https://github.com/user-attachments/files/18167521/template.json) with two layers.
According to https://github.com/jemu75/fhemApp?tab=readme-ov-file#level-element-size with no size set it should sum up in 12 and with 3 elements the size should be 4 each.
As you can see on the picture the divider is on different places - but it should be on the same place:

![SCR-20241217-mgh](https://github.com/user-attachments/assets/b28cd7dd-35a3-4a0f-af67-3b9064af2181)

Seems like the 'info' element is rendered differently than the 'button' element.

**Comment by jemu75** [comment]
Each block for which no width is defined reacts dynamically. Please try to define the width for the two outer blocks in each layer. Then the divider should be visible without offset

**Comment by binford6000** [comment]
This is how i usually do it (or give all components a width). But then the info element still doesn't render correctly:

![SCR-20241217-v5b](https://github.com/user-attachments/assets/f9dbd9d8-0180-4f8d-89f2-95e2cfd00d46)

[info_element.json](https://github.com/user-attachments/files/18171576/info_element.json)

**Comment by Himbi777** [comment]
I can also reproduce the error. 3x info field at the top. A button at the bottom left and right and an info field in the middle. The width on the left and right is set to 3.
![Screenshot_20241217-225245](https://github.com/user-attachments/assets/bb746a8e-ce1c-4a63-9bb7-7deb03c9aef6)

**Comment by Himbi777** [comment]
If only the middle field is defined in width, it works.
![Screenshot_20241217-230303](https://github.com/user-attachments/assets/0b300ef7-babb-44da-a368-f92b105fe8df)

**Comment by binford6000** [comment]
> If only the middle field is defined in width, it works. 

Not on my side. If i set size only in the middle the fendering error moves to that element:

![SCR-20241218-9si](https://github.com/user-attachments/assets/abf6f147-6974-4396-baf6-b3fe56163e5c)

**Comment by binford6000** [comment]
Its also not question of the renderer itself. The error can be reproduced on Gecko, Webkit and Blink.

**Comment by binford6000** [comment]
@jemu75 Could you please reopen the issue? Seems like there is the need for further investigation!

**Comment by binford6000** [comment]
> I noticed the error earlier when I had a button on the left and an info field on the other. I then simply replaced the info field with a button and then just didn't store any command when clicked.

Yes, did this with the vacuum definition above. But thats a workaround. Having an icon **and** text works only with info element.

**Comment by jemu75** [comment]
solved with version 4.6.0 wich is puplished now
