### ISSUE TITLE
Charts für die letzten 24h anzeigen

### ISSUE THREAD

**Issue by DarkShortie** [jemu75/fhemApp#24]
Ich würde gerne an einer Stelle anstatt der letzten 7 Tage gerne die letzten 24h im Chart angezeigt bekommen.

Lässt sich das in den appOptions festlegen?

**Comment by jemu75** [comment]
Bisher noch nicht. Ist aber ein guter Vorschlag. Ich nehme das Feature mit in Angriff.

**Comment by jemu75** [comment]
Ich habe eben v3.7.0 freigegeben. Hier kannst du unter "setup" im Template "chart" den Parameter "daysAgo" verwenden.

**Comment by DarkShortie** [comment]
Danke, funktioniert super. Wenn jetzt noch die Uhrzeiten anstelle des Datums angezeigt wird, wäre es perfekt.
