### ISSUE TITLE
Grafana per iframe o.Ä. einbinden?

### ISSUE THREAD

**Issue by DarkShortie** [jemu75/fhemApp#25]
Als Alternative zu den Charts wäre es eine gute Option auch Grafana Charts einbinden zu können. Aktuell nutze ich sie über das weblink Module in fhem und binde sie als iframe ein.

Grafana ist sehr mächtig und dabei auch sehr performant und wäre gerade bei vielen Datenpunkten bestimmt eine gute Alternative.

Hier mal eine Beispiel Definition
```
define grafanaWohnzimmerHeizung weblink iframe https://meinefhemdomain.de/grafana/d-solo/pTUoZwTMz/fhem?orgId=1&panelId=2&from=now-d&to=now&var-raum=Wohnzimmer
  attr grafanaWohnzimmerHeizung group Heizung
  attr grafanaWohnzimmerHeizung htmlattr width="100%" height="300" frameborder="0" title="Aktueller Verlauf"
  attr grafanaWohnzimmerHeizung nodetaillink 1
```

**Comment by jemu75** [comment]
Aktuell habe ich keine Probleme bzgl. der Performance der Charts. Der Flaschenhals ist eher das Laden der Daten aus den logfiles. Wobei auch hier ca. 3-4 Sek. für Messwerte von 3 Jahren  durchaus okay sind. Hast du Erfahrungswerte was die Ladezeiten von Charts in FHEMApp anbetrifft?

**Comment by DarkShortie** [comment]
Gestern beim ausprobieren war fhem zwischendurch plötzlich etwas langsam, ob es aber an den Charts lag kann ich nicht sicher sagen. Die Daten kommen aus DbLog.

Ich hatte gestern versucht ein Chart zu bauen das links die Soll und Ist Temperatur und rechts die Ventilstellung und Luftfeuchtigkeit anzeigt. Sobald ich aber die zweite Def links hinzugefügt hatte, hat er gar nichts mehr angezeigt. Bei der zweiten Def rechts funktionierte es, es wurde aber beim Mouse Over °C anstatt % angezeigt.
Da das nicht erfolgreich war (und fhem langsam war), kam mir die Idee ob man nicht einfach weiterhin Grafana einbinden könnte.

**Comment by jemu75** [comment]
Hallo, mit der Version 4 von FHEMApp bin ich auf eine neue Chart-Komponente umgestiegen. Ich verwende jetzt Apache eCharts. Die Möglichkeiten zur Erstellung von Charts sind hier nahezu unerschöpflich und auch die Performance bei Verarbeitung großer Datenmengen ist besser als bei der bisher eingesetzten Chart-Komponente in FHEMapp 3.x. Insofern ist es aktuell nicht geplant Grafana zu unterstützen.
