### ISSUE TITLE
[sysmon] Invalid Date

### ISSUE THREAD

**Issue by hydrotec468** [jemu75/fhemApp#28]
Seit v3.6.0 wird in dem Template _sysmon_ bei _Server/Fhem läuft seit: Invalid Date_ angezeigt.

**Comment by jemu75** [comment]
Gibt es noch andere Stellen in der App, an denen das Datum nicht mehr korrekt dargestellt wird? Welches Betriebssystem und welchen Browser hast du im Einsatz?

**Comment by jemu75** [comment]
Das Problem mit der Datumsformatierung bei Firefox und Safari habe ich noch nicht komplett behoben. Das Template sysmon habe ich erstmal auf den letzten Stand zurück gedreht, damit die Zeitstempel bei "FHEM Start" und "System Start" erstmal wieder angezeigt werden.

**Comment by hydrotec468** [comment]
FhemApp v3.7.1

Windows 10 Pro / Vers. 20H2

Edge Vers. 89.0.774.68 (Offizielles Build) (64-Bit) funktioniert (inkl. Infozeile)
Firefox 87.0 (64-Bit) funktioniert (inkl. Infozeile)
Safari (iOS/ipadOS 14.4.2) funktioniert
Safari (iOS/ipadOS 14.4.2) funktioniert in der Infozeile nicht

**Comment by hydrotec468** [comment]
FhemApp v3.8.1

Windows 10 Pro / Vers. 20H2
Edge Vers. 89.0.774.68 (Offizielles Build) (64-Bit) funktioniert (inkl. Infozeile)
Firefox 87.0 (64-Bit) funktioniert (inkl. Infozeile)

Safari (iOS/ipadOS 14.4.2) funktioniert (inkl. Infozeile)

Wallpanel 0.9.4 (Android 8.1) funktioniert (inkl. Infozeile)

Dankeschön :-)
