### ISSUE TITLE
[general] Statuslleiste index.html

### ISSUE THREAD

**Issue by hydrotec468** [jemu75/fhemApp#29]
Besteht die Möglichkeit in der Statusleiste der _index.html_ zusätzllich noch das Datum anzuzeigen?
Wegen mir auch optional.

Hintergrund:
Hab gerade fhemApp auf meinem Wandtablet (8.1 Oreo / Wallpanel 0.9.4) aufgerufen.
Für den Dauerbetrieb würde mir das Datum noch fehlen.

THX ;-)

**Comment by jemu75** [comment]
habe ich eingebaut. Kommt mit dem nächsten Release
