### ISSUE TITLE
[slider] Bei Bewegung Wert anzeigen

### ISSUE THREAD

**Issue by hydrotec468** [jemu75/fhemApp#32]
v3.8.1
Beim Verschieben des sliders befindet man sich im Blindflug welcher Wert angestrebt wird.
Besteht die Möglichkeit den zu setzenden Wert bei Bewegung anzuzeigen?

https://forum.fhem.de/index.php/topic,119470.msg1146658.html#msg1146658

**Comment by jemu75** [comment]
umgesetzt mit v.3.10.0
