### ISSUE TITLE
[panel:setup] Bei "status": noch einen button einfügen (rechte Seite bei Namen)

### ISSUE THREAD

**Issue by hydrotec468** [jemu75/fhemApp#33]
Möglichkeit bei dem Template _"panel"_ einen button einfügen.

Hintergrund:
Ich habe ein Panel mit mehreren _panelItems_ bei denen der button auf die gleiche Gruppe verzweigt ist.
Da währe es schöner, oben neben dem Namen des Panels optional einen button zur Verfügung zu haben, 
und bei den paneltems optional (wie seither auch) den button entfernen.

Bspl.
"setup": {
"status": {
"btn": "mdi-chevron-right",
"link": "/devices/group=zone_apartment_light"
},

**Comment by jemu75** [comment]
Hallo,

mit der neuen Version 4 gibt es weitere Möglichkeiten Panels zu gestalten. Die Version 3.x wird deshalb nicht weiterentwickelt. Schau dir gern mal die neue Version an. Aktuell steht diese als Betaversion zur Verfügung
