### ISSUE TITLE
[general:main] Mehrere "slider" untereinander

### ISSUE THREAD

**Issue by hydrotec468** [jemu75/fhemApp#34]
Bis jetzt kann man bei _"main":_ nur zweimal text nebeneinander, oder einen slider anzeigen lassen.
Besteht die Möglichkeit, das man bei slider auch mehrere untereinander anzeigen lassen kann?

Hintergrund:
Bei den HUE lights gibt es z.B. ct, pct oder bri, die man gut über slider darstellen könnte.
Mit der Farbauswahl wird es vermutlich etwas tricky.

**Comment by jemu75** [comment]
mit v3.16.0 umgesetzt
