### ISSUE TITLE
Ich sehe hier keine Geräte

### ISSUE THREAD

**Issue by gent99** [jemu75/fhemApp#37]
Habe mir jetzt mal einen einfachen Schalter in fhemapp laut Anweisung konfiguriert und sehe diesen in fhemapp nicht. fhemapp wird direkt unter fhem betrieben, keinerlei zusätzlichen server etc. involviert. Attribute laut readme gesetzt. Woran könnte es liegen?

**Comment by jemu75** [comment]
Hat **FHEMApp** eine Verbindung zu FHEM? Du erkennst das an dem grünen Punkt oben rechts in der App.
Hast du in deinem FHEM Device das Attribut `appOptions` gesetzt und dort den Parameter `{ "template": "switch" }` eingetragen?
Hat dein FHEM Device die Attribute `room` und/oder `group` definiert? (Alternativ room bzw. group in appOptions definiert)

Das wären aus meiner Sicht mögliche Ursachen, weshalb ein Template nicht angezeigt wird.
