### ISSUE TITLE
color in Btn option

### ISSUE THREAD

**Issue by MiniBlister** [jemu75/fhemApp#39]
Vielen Dank für die tolle Arbeit. 
Ich möchte sehr kleine Buttons erstellen, dessen aktueller Status lediglich durch die Farbe des Icons unterschieden wird. 
Was ich mir wünsche würde, wäre folgendes:

`"midBtn": ["state:on:mdi-coffee:yellow","state:off:mdi-coffee:red" ]`

Wäre sowas möglich?

**Comment by jemu75** [comment]
kommt mit dem nächsten Release V.3.30.0
