### ISSUE TITLE
keine Möglichkeit die Buttonfarbe bei Verwendung von left/rightMenu zu ändern

### ISSUE THREAD

**Issue by Himbi777** [jemu75/fhemApp#40]
Bei Verwendung von leftClick / rightClick kann bei dem entsprechenden Button (leftBtn / rightBtn) per Definition die Farbe des Icons geändert werden. 
Wenn anstatt Click die Menu-Funktion mit dem Button verknüpft wird, kann die Farbe des Buttons nicht mehr angepasst werden.
Eine entsprechende Anpassung wäre schön.

Gruß Gerhard

**Comment by jemu75** [comment]
mit v.3.36.2 gelöst
