### ISSUE TITLE
Commands die mit 'set' beginnen sind nicht ausführbar

### ISSUE THREAD

**Issue by Mockabear** [jemu75/fhemApp#46]
Es scheint ein Problem mit Commands zu geben die mit 'set' beginnen. Bei solchen Commands muss immer der komplette Set-Befehl im Template verwendet werden, damit selbige ausgeführt werden.

Die folgende Kurzform funktioniert z.B. nicht **nicht**:

`"leftClick": ["SlateOrientationState::setOrientation %i15"]`

Wird das komplette Set-Kommando mit Device-Namen angegeben, wird der Befehl ausgeführt:
CodeAuswählen
`"leftClick": ["SlateOrientationState::set tahoma_9183101 setOrientation %i15"]`

**Comment by jemu75** [comment]
Problem sollte mit dem Release 3.36.4 behoben sein.

**Comment by Mockabear** [comment]
Nur zur Info, falls hier jemand drüber stolpert: Der Fix ermöglicht es statt des Devicenamens den Platzhalter "%d" zu verwenden.
Für Readings / Commands die mit "set" beginnen muss das set-Kommando also ausgeschrieben werden:
`"leftClick": ["SlateOrientationState::set %d setOrientation %i15"]`
