### ISSUE TITLE
Instalationsprobleme

### ISSUE THREAD

**Issue by SamNitro** [jemu75/fhemApp#51]
Hey habe schon Probleme bei der Installation, habe die [02_FHEMAPP.pm] ins FHEM Verzeichnis gepackt und die nötigen Rechte Vergeben.

Device angelegt, neu gestartet. 
Im Device selber ist folgender Eintrag:
`configLastRead
Error on reading ./conf/myapp_config.fhemapp from database! `

und im Log:
`gzip: stdin: unexpected end of file
fhemApp-3.36.4/www/fhemapp/update.sh
tar: Child returned status 1
tar: Error is not recoverable: exiting now`

Benutze eine Datenbank wo Fhem-Config und Dateien abgelegt werden können, kann es daran liegen?

Gruß Patrick

**Comment by jemu75** [comment]
Hallo Patrick,

vielen Dank für's "Vorabtesten". Ich habe mich in die Weiterentwicklung von FHEMapp mit Benni (fhem Forum) reingeteilt. Er hat das FHEM-Modul erstellt und ich habe das Frontend in Arbeit. Ich informiere Benni zu deinem Problem. 

Gruß
Jens

**Comment by jemu75** [comment]
Hallo Patrick,

ich habe inzwischen eine Beta-Version veröffentlicht. siehe dazu auch die Infos im FHEM-Forum unter [https://forum.fhem.de/index.php?topic=137239.0](url) Bitte teste nochmal mit der aktuellen Version und lass mich wissen, ob es jetzt funktioniert.

Gruß
Jens

**Comment by jemu75** [comment]
Hallo Patrick,

das Modul ist seit heute offizieller Bestandteil von FHEM und wird mit den Updates ausgeliefert. Die bisherigen Tests haben gezeigt, dass das Modul einwandfrei arbeitet. Ich würde deine Anfrage deshalb schließen. Sollte dir dennoch was bei der Installation des Modules in FHEM auffallen, dann erstelle gern ein neues Issue.

Grüße
Jens
