### ISSUE TITLE
Bereitstellung von Standard-Templates

### ISSUE THREAD

**Issue by jemu75** [jemu75/fhemApp#52]
Es soll eine Auswahl von Standard-Templates zur Verfügung stehen, damit man einfach mit FHEMApp starten kann. Wünschenswert ist es, dass die Standard-Templates von Version 3.x auch in Version 4 zur Verfügung stehen, damit der Umstieg auf **FHEMApp4** erleichtert wird.

**Comment by binford6000** [comment]
Besonders das 'template-scenes' ist interessant, da es alle verfügbaren Szenen eines LightScene-Devices auslesen kann und man nicht manuell die Menüeinträge füllen muss.

**Comment by jemu75** [comment]
bereitgestellt mit v4.0.41-beta
