### ISSUE TITLE
Umschaltung Tag/Nacht-Modus über FHEM

### ISSUE THREAD

**Issue by jemu75** [jemu75/fhemApp#53]
Es soll möglich sein, den Tag/Nacht-Modus in **FHEMApp4** direkt von FHEM aus zu steuern. Wenn ein bestimmtes _reading_ einen definierten Wert enthält, soll **FHEMApp4** automatisch in den entsprechenden Farbmodus wechseln, wenn die App gerade geöffnet ist bzw. wenn sie geöffnet wird. 

Zu definieren ist noch, was in dem Fall mit dem URL-Parameter "?dark=0|1" passiert. Hat dann der URL-Parameter oder das FHEM Reading den "Vorrang"

**Comment by benni1972** [comment]
2 Ideen:

1. Ist ein URL Parameter für darkmode angegeben, egal ob 1 oder 0, hat der Vorrang, andernfalls greift die definierte Umschaltbedingung mittels Reading oder falls es die auch nicht gibt eben der default (dark)
2. Es dem User überlassen und dort, wo die Bedingung(en?) für das Umschalten definiert sind, über einen zusätzlichen Parameter (force 1/0) festlegbar machen, ob die Bedingung die URL übersteuern darf oder nicht.

**Comment by jemu75** [comment]
Hallo Benni,

ich bin dem Vorschlag von Sebastian gefolgt und prüfe ab **v4.0.24-beta** die Systemeinstellung vom Betriebssystem. Damit ergibt sich folgendes Verhalten. Wenn kein URL-Parameter (dark=0 bzw. dark=1) festgelegt ist, übernimmt **FHEMApp** die Einstellung vom Betriebssystem und reagiert auch auf das Umschalten im Betriebssystem während der Laufzeit. Sobald der URL-Parameter `dark` verwendet wird, so hat dieser Priorität. Zusätzlich kann zu jeder Zeit über das Optionsmenü vom Benutzer der Tag/Nacht-Modus umgeschaltet werden. Ein weiterer Weg wäre, das Festlegen bzw. Umschalten aus FHEM (über ein beliebiges device+reading) heraus, wie oben beschrieben.

Dann würde sich folgende Reihenfolge ergeben:
1. Einstellung aus Betriebssystem
2. Einstellung aus FHEM (hat Vorrang vor 1.)
3. Einstellung aus URL (hat Vorrang vor 1. und 2.)
4. Umschaltung durch Benutzer in der UI (hat Vorrang vor 1., 2. und 3.) 

Somit wäre der zusätzliche "force" Parameter nicht nötig.

**Comment by jemu75** [comment]
gelöst mit v4.0.35-beta
