### ISSUE TITLE
Darkmode basierend auf den Systemeinstellungen des Betriebsystems

### ISSUE THREAD

**Issue by binford6000** [jemu75/fhemApp#56]
Momentan bietet die FHEMApp4 lediglich die Möglichkeit, den Darkmode entweder 
- manuell im Einstellungs-Menü 
![SCR-20240228-ca7](https://github.com/jemu75/fhemApp/assets/29679540/05523ba4-d7b3-4db3-a6ab-50ade9323ad5)

- oder über einen URL-parameter `?dark=0` einzustellen.

Am anwenderfreundlichsten wäre es mMn., wenn der Darkmode sich wie andere moderne Webanwendungen als Default an den Systemeinstellungen des Betriebsystems orientieren könnte. Manuelles Ändern sollte auch weiterhin über das Einstellungsmenü 
möglich sein.

VG Sebastian

**Comment by jemu75** [comment]
Hallo Sebastian,

ich habe diese Funktionalität erweitert. Dein Vorschlag wird mit v.4.0.24-beta umgesetzt.
