### ISSUE TITLE
Raw-Mode und UI-Mode nicht synchron

### ISSUE THREAD

**Issue by benni1972** [jemu75/fhemApp#58]
Bei der Editierung von Vorlagen sind der Raw-Mode und der "normale" Eingabemodus (UI-Mode) von den Einstellungen her nicht synchron.

**Beispiel:** Neue Vorlage -> Allgemein: Autor und Datum eingeben -> Speichern -> Umschalten auf Raw-Mode ... et voilà!

-> der Raw-Mode hat weder den Autor, noch das Datum drin.
-> Wenn man jetzt im Raw-Mode nochmal speichert, sind die zuvor im UI-Mode gemachten Einstellungen futsch!

**Comment by benni1972** [comment]
Umgekehrt funktioniert es übrigens. Wenn im Raw-Mode geändert wird sind beim anschließenden Wechsel auf den normalen Modus alle Änderungen aus dem Raw-Mode vorhanden.

**Comment by jemu75** [comment]
gefixt mit v4.0.22-beta
