### ISSUE TITLE
Reihenfolge von (Bedingungs-)Einträgen im UI änderbar machen.

### ISSUE THREAD

**Issue by benni1972** [jemu75/fhemApp#59]
Es fehlt im UI an vielen Stellen eine einfache Möglichkeit, die Reihenfolge von Einträgen zu ändern.
Die meisten Einträge werden in der Reihenfolge nach, in der sie in der Konfiguration stehen ausgewertet, bzw. im UI angezeigt.

Bspw. werden mehrere Bedingungen für das Anzeigen von Icons solange ausgewertet, bis der erste true ergibt. Daher muss hier immer mal wieder die Reihenfolge geändert werden, damit die am wenigsten "gierige" Bedingung vor einer "gierigeren" Bedingung ausgewertet wird.

Beispiel Statusbar:

```
"bar": [
   "door_state:open:100:error",
   "lock_state:unlocked:100:warning"
   "lock_state:locked:100:success",
   "::90:pink"
]
```
Die Auswertung der Bedingungen erfolgt dabei genau in der Reihenfolge (top-down), wie sie hier angegeben sind.

So dient der letzte Eintrag, quasi als letztes "ELSE" der Bedingungen. Die ist immer erfüllt, wenn keine andere erfüllt ist. Stünde die am Anfang, würde sie immer auch zuerst erfüllt werden und die anderen würden nie erreicht werden.

Im Raw-Mode kann ich das problemlos umsortieren (für mich grundsätzlich OK ;) ). 
Im UI-Mode müsste ich derzeit die Einträge per Copy & Paste umständlich Feld für Feld austauschen.

Außerdem gibt es nicht überall einen Raw-Mode, bspw bei  "Navigation", entweder auch hier Feld für Feld per C&P umsortieren oder über das Config-File bearbeiten (i.d.R. für die meisten nicht gut!)

Von daher wäre es schön,  wenn man im UI entweder per Drag & Drop, oder per Buttons (Pfeil hoch, Pfeil runter) die Einträge verschieben könnte.

Kategorie: Nice-To-Have

**Comment by jemu75** [comment]
gelöst mit v4.0.23-beta
