### ISSUE TITLE
mdi-Icons direkt von FHEM laden

### ISSUE THREAD

**Issue by jemu75** [jemu75/fhemApp#6]
Die MD Icons sind inzwischen auch unter fhem verfügbar und müssten zumindest bei einer Installation unter fhem nicht von extern geladen werden. [siehe](https://forum.fhem.de/index.php/topic,117254.msg1116330.html#msg1116330)

**Comment by jemu75** [comment]
Icons werden jetzt lokal geladen

**Comment by binford6000** [comment]
Hallo Jens,
in dem angesprochenen [Thread](https://forum.fhem.de/index.php/topic,117254.0/all.html) werden ja die Templarian  - also mdt - Icons geladen. Das Präfix ist also mdt.
Wenn ich diese Icons angebe werden aber keine Icons angezeigt. Wie werden die Icons denn tatsächlich lokal geladen?
VG Sebastian

**Comment by jemu75** [comment]
Hallo Sebastian,

die Icons werden lokal geladen. Allerdings werden die Icons aus dem Ordner ../fhemapp/fonts/ geladen. Ich greife also nicht auf Icons zu, die an anderer Stelle unter FHEM abglegt sind.

Beste Grüße
Jens.

Am 28. April 2021 um 13:38:23 +02:00, hat binford6000 ***@***.***> geschrieben:
