### ISSUE TITLE
Spracheinträge im UI alphabetisch sortieren

### ISSUE THREAD

**Issue by benni1972** [jemu75/fhemApp#60]
Ich nutze bisher ziemlich konsequent die Möglichkeit der  "Sprachen" in FHEMApp. So sind inzwischen dort einige Einträge zusammengekommen.

Die einzelnen Sprachbausteine werden im UI in den Einstellungen immer in derr Reihenfolge angezeigt, in der Sie erstellt wurden.
Schön wäre, wenn man die sortieren lassen könnte und zwar wahlweise nach Name oder nach den einzelnen Sprachen (DE, EN, ...)

So könnte man sich schnell einen Überblick verschaffen, was denn schon da ist.

Zusätzlich wäre eine Filterfunktion (Suche) praktisch, ähnlich wie bei den Vorlagen.
Aktuell habe ich nur die Browser-Suche als Möglichkeit.

Kategorie: Nice-To-Have

**Comment by jemu75** [comment]
gelöst mit **v4.0.24-beta**
