### ISSUE TITLE
Einfacherer Zugriff auf die, in Vorlagen definierten Deviece-Keys

### ISSUE THREAD

**Issue by benni1972** [jemu75/fhemApp#62]
Es wäre praktisch, wenn man bei der Einrichtung eines Panels, wenn man eine Vorlage auswählt, bei der Device-Zuordnung eine Auswahl der Keys hat, die die Vorlage als Device erwartet.

Dazu wäre es wahrscheinlich Sinnvoll, wenn man die device-keys in der Vorlage nicht AdHoc einbaut, sondern Sie quasie zuvor in den Allgemeinen Einstellungen der Vorlage erst deklarieren müsste, ggf. sogar inkl. einer kurzen Beschreibung und evtl. der Angaber des erwarteten Device-Type, sofern möglich.

Das wäre u.a. auch bei der Übernahme fremder Vorlagen hilfreich. Dann muss man sich nicht erst durch das json arbeiten umd alles keys zu finden. Auch wäre es hilfreich.

Ich vergesse ja selbst bei meinen Eigenen Vorlagen ständig, welche device-keys meine Vorlagen so "anbieten". :D

Wenn eine Vorlage neben, mit device-Keys versehene Readings (& Co.), auch welche ganz ohne Key verwendet, sollte irgendwei klar sein, welcher Device-Typ dafür erwartet wird. Im Moment wird wahrscheinlich einfach das erste angegebene Device verwendet, bzw. das erste, dass ein entsprechendes Reading (&Co.) hat. (reine Spekulation)

Eventuell ist es aber einfacher, bei den Vorlagen einen Beschreibungstext hinterlegen zu können um die Funktion näher zu erläutern. Mit dieser Möglichkeit könnte man theoretisch das oben gewünschte, zumindest informativ, erschlagen.
Wenn man sich diese Info bei der Panel-Einrichtung dann auch noch anzeigen lassen könnte (?-Button), wäre das wahrscheinlich die einfachste Umsetzungsmöglichkeit für diesen Feature-Wunsch.

Kategorie: hilfreich!

**Comment by jemu75** [comment]
Hallo Benni,

lass mich bitte mal wissen, ob ich dieses Issue mit dem inzwischen implementierten Assistenten schließen kann.

Danke Dir!
Jens

**Comment by benni1972** [comment]
Hallo Jens, 

ja! Für mich passt das!
Wie im Forum bereits geschrieben: Perfekte Umsetzung!

Gruß Benni.
