### ISSUE TITLE
QuickEdit von Panels (oder der  entsprechenden Vorlage)

### ISSUE THREAD

**Issue by benni1972** [jemu75/fhemApp#63]
Praktisch wäre es, wenn man aus der normalen Bedienansicht bspw. per Doppelklick auf die Titelleiste oder zustzlichem Button in der Titelleiste des Panels direkt in die Bearbeitung des entpsrechenden Panels springen könnte oder per Shift-Doppelklick (o.ä.) oder auch per Button in die entsprechende Vorlage des Panels springen könnte.

Das sollte u.U. nicht generell für jeden Verfügbar sein und könnte ja per URL-Parameter und/oder Einstellung aktiviert werden.
Dann bräuchte es (wenn es keine Buttons sind) einen entsprechenden Indikator.

Kategorie: Nice-To-Have

**Comment by jemu75** [comment]
Ich könnte diese Funktion mit dem Loglevel7 aktivieren. So mache ich das beispielsweise schon, um die Internals anzuzeigen.

**Comment by benni1972** [comment]
loglevel 7 ... Passt!

**Comment by jemu75** [comment]
mit **v4.0.39-beta** umgesetzt

**Comment by benni1972** [comment]
Servus Jens,

der Sprung in die entsprechende Panel-Konfig klappt einwandfrei. Danke! 

Meinst du, du könntest auch noch den wahlweisen Sprung in die Vorlage des Panels (falls eine verwendet wurde) realisieren?

Per URL-Route geht das ja nun grundsätzlich schon ;)

Gruß Benni

**Comment by jemu75** [comment]
Hallo Benni,

ja, daran hatte ich auch gedacht. Wenn man das direkt vom Panel macht, dann würde ggf. noch ein Button in der Kopfzeile dazukommen. Alternativ hatte ich überlegt, den "Sprung" zum Template in der Panelkonfiguration beim Element Template einzubauen. Dann könnte man vom Template zur Panelkonfiguration und von hieraus in die Templatekonfiguration springen. Was meinst du dazu?

Grüße
Jens

**Comment by benni1972** [comment]
Hallo Jens,

Der Sprung vom Template aus der Panel-Konfiguration heraus ist zwar logisch, aber definitiv zu kompliziert!
Dann lieber einen zusätzlichen button um vom Panel direkt zu springen. Warum nicht, wir befinden uns schließlich in Loglevel 7 ;)

Die Idee ist ja, dass ich beim Panel sehe, dass eine Änderung notwendig ist und dann möchte ich ohne Umweg direkt an die passende Stelle springen, entweder in der Panel-Konfiguration selbst, oder eben im zugrunde liegenden Template.

Keine Ahnung, ob das evtl. mittels Key+Klick machbar ist, wie von mir bereits vorgeschalgen. Also bspw. ein Klick auf den Stift-Button bei gedrückter Modifier-Taste (Shift, Alt, Strg, .... oder whatever Kombi) Ansonsten ist ein zusätzlicher Button, wie schon gesagt, in Loglegvel 7, denke ich durchaus vertretbar.

Kannst ja in Ruhe darüber nachdenken, das ist wirklich nur nice-to-have!

Grüße
Benni.

**Comment by jemu75** [comment]
gelöst mit v4.0.41-beta
