### ISSUE TITLE
Level Element Image: Bedingung zum Anzeigen hinzufügen

### ISSUE THREAD

**Issue by binford6000** [jemu75/fhemApp#64]
ZB. für den Anwendungsfall der Anzeige von Coverart in einem Musik-/Mediaplayer wäre es schön, wenn die Anzeige der Coverart an ein Reading geknüpft werden könnte. Sprich das Cover wird nur angezeigt, wenn die Wiedergabe läuft. Ansonsten entweder keine Anzeige oder auch ein Ersatzbild.

**Comment by jemu75** [comment]
Hast du schon probiert, den Parameter `show` für die Ebene, in der das Bild angezeigt wird, zu verwenden. Damit könnte man das realisieren.

**Comment by binford6000** [comment]
Das ist korrekt, aber wenn das Image nicht alleine in einer Ebene liegt wie hier zu sehen dann funktioniert das so nicht da show ja für die gesamte Ebene definiert wird:

<img width="1150" alt="image" src="https://github.com/jemu75/fhemApp/assets/29679540/1d91fa6d-b83b-4845-85c6-cc7db1b53fc5">

**Comment by jemu75** [comment]
Ich habe die Coverbilder in Verbindung mit einem Sonos System im Einsatz. Das Verhalten in meinem Template ist faktisch wie in der Sonos App. D.h. wenn ein Coverbild vorhanden ist, dann wird dieses angezeigt. Ansonsten wird nichts angezeigt. Wie würdest du die Bedingung definieren und was soll dann passieren?

**Comment by binford6000** [comment]
> Ich nutze gerade folgende Definition in meinem Sonos Template currentAlbumArtURL::%s

Ich tippe mal du hast das native SONOS-Modul in FHEM aktiv. Was steht denn da drin wenn nichts gespielt wird? Oder ist das Reading schlichtweg nicht vorhanden? Ich nutze sonos2mqtt und da bleibt das zuletzt gespielte Coverbild im Reading `currentTrack_albumArtUri::%s` stehen.

**Comment by jemu75** [comment]
Ja, ich habe das native Sonos Modul im Einsatz. Das liefert folgendes im Reading, wenn kein Coverbild vorhanden ist. 
![Screenshot_20240304_204525](https://github.com/jemu75/fhemApp/assets/80094691/4ca8bff1-7ff8-4a48-93d7-266172c657f3)

**Comment by jemu75** [comment]
Wenn das Reading bei dir leer bleibt, falls kein Coverbild existiert, dann kann man das ggf. via regexp prüfen. Bzw. Wenn das Reading z.B. sowas wie jpg enthält, dann Coverbild (%s) anzeigen. Und danach eine weitere Definition, die z.B. auf ein alternatives Bild zeigt.

**Comment by binford6000** [comment]
Ja ok. Muss ich dann in FHEM abfangen.

**Comment by jemu75** [comment]
Ich denke, du musst das gar nicht in FHEM abfangen. Du kannst einfach 2 Definitonen für das Cover erstellen.
1. Definition `currentTrack_albumArtUri:jpg:%s`
2. Definition `::<alternativer_bildpfad_und_bild.jpg>`

Es wird zuerst geprüft, ob im Reading **currentTrack_albumArtUri** der Wert **jpg** enthalten ist. Wenn dem nicht so ist (einschließlich, wenn das Reading nicht existiert) dann greift die 2. Definition.

Melde dich gern, wenn Du noch Fragen dazu hast.

**Comment by binford6000** [comment]
Das passt so für mich. Danke für den Denkanstoß!
