### ISSUE TITLE
Level Element Menu: Änderung des Icons zulassen

### ISSUE THREAD

**Issue by binford6000** [jemu75/fhemApp#65]
Im Element menu ist das icon 'dots-vertical' fest verdrahtet. Es wäre schön, wenn man hier das icon auch auf zB. 'menu' für ein Auswahlmenü einstellen könnte.

**Comment by jemu75** [comment]
Ja, das stimmt. Das werde ich mit erweitern. 🙂

**Comment by jemu75** [comment]
gelöst mit v4.0.23-beta
