### ISSUE TITLE
Speicherung der Einstellungen zur Anzeige der Panels/Vorlagen/...

### ISSUE THREAD

**Issue by binford6000** [jemu75/fhemApp#66]
Momentan werden die Einstellungen **Elemente pro Seite** von Panels und Vorlagen nicht gespeichert. IdR. hat man aber soviele Panels bzw. Vorlagen, dass die Std.-Einstellung **10** zu wenig ist. Hier wäre es hilfreich, wenn die (letzte) Einstellung gespeichert werden würde.

<img width="1151" alt="image" src="https://github.com/jemu75/fhemApp/assets/29679540/9c2b0bec-d63c-4164-8a95-263db9225a01">

**Comment by jemu75** [comment]
Hallo Sebastian,

ich werde das mit **v4.0.24-beta** anpassen. Die Elemente pro Seite werden in der aktuellen Sitzung gespeichert, sodass diese nicht immer wieder auf 10 Elemente zurückspringen, sobald man ein Panel bzw. ein Template editiert.

**Comment by jemu75** [comment]
gelöst mit **v4.0.24-beta**
