### ISSUE TITLE
Vererbung von Template zu Panel

### ISSUE THREAD

**Issue by binford6000** [jemu75/fhemApp#67]
**Aktuelles verhalten:** 
Keine 'Vererbung' von Eigenschaften wie _Navigation_. D.h. Einträge im Template werden von Einträgen im Panel überschrieben.

Aus Template:
`::groups->lights`

plus Panel:
`::rooms->kitchen`

wird dann in Summe:
`"navigation": [
			"::rooms->kitchen"
		]`

**Angedachtes Verhalten:**
Bei manchen Gerätetypen wie Lichter oder Steckdosen wäre es aber von Vorteil, im Template quasi eine 'Basis-Navigation' zu haben und diese im Template mit weiteren Positionen zu erweitern anstatt zu überschreiben.

Aus Template:
`::groups->lights`

plus Panel:
`::rooms->kitchen`

wird dann in Summe:
`"navigation": [
			"::rooms->kitchen",
			"::groups->lights"
		]`

**Comment by jemu75** [comment]
Hallo Sebastian,

ich hatte im Zuge der Entwicklung auch über solche Szenarien nachgedacht. Das "Vermischen" der Definitionen aus Panels und Templates habe ich damals nicht implementiert. Das die Einstellungen vom Template durch Einstellungen vom Panel überschrieben werden, ist bewusst gewählt, da die normalen Definitionen ansonsten nicht mehr korrekt funktionieren würden. Denn hier gilt ja: die erste zutreffende Definition wird verwendet.

Es gibt 3 Sonderfälle, in denen alle zutreffenden Definitionen verwendet werden. Das sind *panel-navigation*, *main-menu* und *cahrt-serie*.

Ich würde das Verhalten also ungern zu Lasten aller anderen Panel Elemente verändern. In deinem Beispiel würde ich vorschlagen, alle Navigationspunkte in den Panels zu hinterlegen und im Template dann komplett wegzulassen.

Grüße
Jens
