### ISSUE TITLE
Erweitert-Schalter im Standard ein wenn erweiterte Definitionen vorhanden sind

### ISSUE THREAD

**Issue by binford6000** [jemu75/fhemApp#68]
**Aktuell:**
- Der Schalter 'erweitert' ist _immer_ deaktiviert, obwohl dort Definitionen wie zB. 'navigation' vorhanden sind:

![image](https://github.com/jemu75/fhemApp/assets/29679540/79df110c-b417-456d-8ce0-c2297eb45e08)

![image](https://github.com/jemu75/fhemApp/assets/29679540/5d48370b-d0ec-4154-8f30-0e1ec568fb02)

**Vorschlag:**

- Der Schalter 'erweitert' ist _immer dann_ aktiviert, sobald eine Definition wie zB. 'navigation' vorhanden ist.

So würde es dem Benutzer direkt auffallen, dass erweiterte Definitionen im Panel gemacht wurden/vorhanden sind.

**Comment by jemu75** [comment]
Hallo Sebastian,

vielen Dank für den Hinweis. Das war in der Tat noch ein Fehler. Dieser wird mit dem nächsten Release **v4.0.24-beta** behoben.

**Comment by jemu75** [comment]
gelöst mit **v4.0.24-beta**
