### ISSUE TITLE
Nach Größenänderung des Browserfensters wird das Einstellungen-Menü abgeschnitten

### ISSUE THREAD

**Issue by binford6000** [jemu75/fhemApp#69]
Nach einer Größenänderung des Browserfensters wird das Einstellungen-Menü abgeschnitten:

![image](https://github.com/jemu75/fhemApp/assets/29679540/7080d4bc-fc61-4c17-a55f-685c92c40025)

Nach einem Reload der Seite im Browser oder über 'Aktualisieren' in den Einstellungen wird das Menü wieder korrekt angezeigt.

**Comment by jemu75** [comment]
Hallo Sebastian,

ich konnte das bei mir mit der aktuellen Version von _vuetify_ ebenfalls nachstellen. Es sieht sehr wahrscheinlich nach einem Fehler im vuetify-Framework aus, denn ich habe das Optionsmenu genau nach Vorgabe umgesetzt. Interessant ist auch, dass das Menu in dem Fall bei mehrmaligem Öffnen und Schließen jedes Mal etwas breiter wird und am Ende auch an der richtigen Stelle (also nicht ganz rechts am Bildrand) platziert wird. 
Ich lass dieses issue erstmal offen und beobachte, ob es mit dem nächsten _vuetify_ Release behoben ist.

Grüße
Jens

**Comment by jemu75** [comment]
Fehler bestätigt. Wird mit v4.1.3 behoben

**Comment by jemu75** [comment]
behoben mit v4.1.3
