### ISSUE TITLE
Geringe Anzahl der Zeichen in der Infozeile 

### ISSUE THREAD

**Issue by binford6000** [jemu75/fhemApp#71]
Die Infozeile zeigt bei V3 wesentlich mehr Text an als bei V4 (siehe Bilder).
Bei V4 ist sogar nur left1/left2 definiert und dennoch werden viel weniger Zeichen angezeigt.

V3:
![image](https://github.com/jemu75/fhemApp/assets/29679540/e3183b68-47ce-4be5-893a-0c6c4ec73562)

V4:
![image](https://github.com/jemu75/fhemApp/assets/29679540/18dfda13-e105-4e03-9c19-fed02073517e)

**Comment by jemu75** [comment]
gelöst mit **v4.0.25-beta**

**Comment by binford6000** [comment]
Moin Jens,
es werden jetzt ALLE Zeichen angezeigt - und zwar zweizeilig:

![SCR-20240312-bma](https://github.com/jemu75/fhemApp/assets/29679540/840e6693-8c5a-484a-a0df-494cf057bc01)
