### ISSUE TITLE
02_FHEMAPP.pm: get rawconfig Befehl + alles markieren markiert auch alles in FHEMWEB

### ISSUE THREAD

**Issue by binford6000** [jemu75/fhemApp#73]
**Aktuell:**
Über das FHEM-Modul und den get-Befehl `get <device-name> rawconfig` kann man die gesamte Konfiguration von FHEMapp V4 anzeigen lassen. Möchte man nun mit `STRG-A` / `CMD-a` alles markieren um es in eine Textdatei zu speichern, wird auch der gesamte Inhalt von der aktuellen FHEMWEB Seite mit kopiert:

![image](https://github.com/jemu75/fhemApp/assets/29679540/a6db5bce-9595-47de-b24f-63f2da0ddb63)

Die ersten ca. 150 Zeilen im kopierten Text enthalten somit nur FHEMWEB Text anstatt des reinen JSON-Teils.

Andere getestete Browser (Brave, Safari) verhalten sich exakt identisch.

**Verbesserung:**
Wie der Name des get-Befehls andeutet, sollte nur die reine FHAMapp config (JSON) kopiert werden und nicht auch das gesamte Browserfenster im Hintergrund.

**Comment by jemu75** [comment]
Hallo Sebastian,

zum Kopieren der Konfiguration, empfehle ich direkt in FHEMApp zu gehen. Wenn du das loglevel auf 7 setzt oder direkt die "internals" aufrufst, kannst du die Konfig einfach über den Kopieren Button in die Zwischenablage übernehmen.

Wenn du die Internals direkt aufrufen möchtest, geht das über `http://fhem:8083/fhem/fhemapp4/index.html#/myapp/internals`

Hilft dir dieser Vorschlag? 🙂

**Comment by binford6000** [comment]
Ja das hilft. Bei näherem Betrachten ist es vermutlich auch eher ein Browser Problem und keines von der FHEMApp.

**Comment by benni1972** [comment]
Grundsätzlich ist das eher ein Browser-Problem.

Ab der nächsten FHEMAPP-Version wird es ein 'set getConfig' am Device geben. Damit werden die Daten ohne den "OK-Dialog" drumherum, direkt im Fenster ausgegeben.

Außerdem wird es dann optional möglich sein, die Config Files im "Edit Files" Bereich von FHEM  verfügbar zu machen.
Das muss aber explizit und je FHEMAPP-Device separat, per Attribut enigestellt werden. Denn das manuelle Editieren von Config-Files sollte generell nicht mehr das Mittel der Wahl sein! ;)

Ansonsten kann man ein FHEMAPP-Device auch immer ganz einfach per copy-Command duplizieren, damit wird dann auch eine Kopie des Config-Files für die neue Kopie des Device erzeugt. Und erhält damit quasi auch so eine Art Backup.
In dem Fall sollte allerdings im DEF der Kopie "none" für den Pfad vorgegeben werden, weiterhin sollte das attribut "disabled" gesetzt sein.
