### ISSUE TITLE
Backup / Restore der gesamten FHEMapp V4 config

### ISSUE THREAD

**Issue by binford6000** [jemu75/fhemApp#74]
**Aktuell:**
Momentan gibt es nur die Möglichkeit, auf OS-Ebene das config-File zu sichern oder über FHEMWEB und im Modul 02_FEMAPP.pm über den Befehl `get <device-name> rawconfig` (siehe auch #73) die gesamte Konfiguration zu sichern.

**Vorschlag:**

- In FHEMapp unter 'Einstellungen' die Möglichkeit anbieten, die gesamte Konfiguration - ähnlich wie es momentan ja schon bei einzelnen Panels oder Vorlagen der Fall ist - per c&p zu sichern:

<img width="769" alt="image" src="https://github.com/jemu75/fhemApp/assets/29679540/e2302aec-c93e-4844-a53b-fbe45a695bb6">

.
.    
- Noch besser wäre womöglich direkt einen Download der gesamten config als .json Datei zu erlauben. Man könnte die Funktion evtl. auch hinter `?loglevel=7`'verstecken'?

**Comment by jemu75** [comment]
Hallo Sebastian,

du kannst dir die gesamte Konfiguration aus den Einstellungen bereits kopieren und dann für dich sichern. Dazu kannst du die Internals von **FHEMApp** aufrufen. Dort wird dir die gesamte Konfiguration angezeigt und es gibt die Möglichkeit diese zu Kopieren.
Der Aufruf der Internals kann über das loglevel 7 oder direkt über die URL z.B. `http://fhem:8083/fhem/fhemapp4/index.html#/myapp/internals` erfolgen.
