### ISSUE TITLE
Falsche Expanded-Darstellung bei Charts die als reines Panel erstellt wurden

### ISSUE THREAD

**Issue by binford6000** [jemu75/fhemApp#75]
Mein erstes Panel habe ich über ein Template erstellt. Ein zweites Panel habe ich ohne Template gebaut da es eh sehr individuell ist und Templates bei Charts und bei Panels mit mehreren Devices wenig Sinn machen...

Beim Erstellen des Charts als Panel ist mir dann aufgefallen, dass Expanded sich im Panel anders Verhält und angezeigt wird als mit einem Template. Wobei bei Verwendung von Template mMn. die korrekte Anzeige darstellt (siehe Bild). Die einzelnen .json Dateien habe ich angehängt. Vielleicht habe ich auch nur einen Knoten im Kopf...

![image](https://github.com/jemu75/fhemApp/assets/29679540/432bb061-a2f8-4e30-b214-18cbb876ce6c)

[AL_panel.json](https://github.com/jemu75/fhemApp/files/14556362/AL_panel.json)
[AL_panel_via_template.json](https://github.com/jemu75/fhemApp/files/14556363/AL_panel_via_template.json)
[AL_via_panel.json](https://github.com/jemu75/fhemApp/files/14556364/AL_via_panel.json)

**Comment by jemu75** [comment]
Hallo Sebastian,

in der **AL_via_panel.json** fehlt die Angabe der Höhe für die Ebene im Vergleich zu der **AL_panel.json** -> "height": "250px"
