### ISSUE TITLE
Icon Vorschau in allen Bereichen - nicht nur in Navigation in den Einstellungen

### ISSUE THREAD

**Issue by binford6000** [jemu75/fhemApp#76]
**Aktuell:**
In den Einstellungen unter Navigation kann man Icons angeben und es wird eine Vorschau angezeigt falls vorhanden.
Das ist in der Panel/Template-Konfiguration nicht vorhanden.

![SCR-20240312-mj2](https://github.com/jemu75/fhemApp/assets/29679540/19e605dd-9ec3-42b8-9d4d-e38c81667716)

**Vorschlag:**
In jedem Feld welches auch ein Icon darstellen könnte wird ggf. eine Icon Vorschau zB. vor dem Hilde-Button angezeigt.

**Comment by jemu75** [comment]
Hallo Sebastian,

in den Definitionen ist die Vorschau der Bilder nur bedingt machbar. Man kann innerhalb von Definitionen die Icons zwar durchaus als festen Wert (z.B. in Form von `mdi-check`) angeben. Sie lassen sich aber auch dynamisch (entweder über den Wert eines readings `%s` oder über das _iconMapping_ befüllen. In diesen Fällen würde die Vorschau innerhalb der Definition nicht funktionieren. Ich denke, über die Panelvorschau (rechts) ist das schon ganz gut gelöst und würde diesen Featurewunsch deshalb nicht weiter verfolgen. Hoffe das ist okay. 

Jens
