### ISSUE TITLE
Anzeige Datum/Zeit wird nicht vom FHEM Server angezeigt

### ISSUE THREAD

**Issue by binford6000** [jemu75/fhemApp#77]
**Aktuell:**
Da ich gerade aus dem Ausland über VPN auf die FHEMApp zugreife sehe ich, dass Datum + Uhrzeit meines Macbooks
angezeigt wird und nicht die des FHEM Servers. Letzteres macht aber mMn. mehr Sinn da alle Anzeigen ja auch
auf der lokalen Zeit basieren.

**Vorschlag:**
Anzeige von Datum/Uhrzeit in absteigender Reihenfolge:

1. FHEM-Server (FHEMApp läuft auch auf dem FHEM-Server)
2. Server auf dem FHEMApp läuft (!= FHEM-Server)
3. Client

**Comment by benni1972** [comment]
Idee dazu:

Es interessiert tatsächlich die Zeit von FHEM und nicht die Client-Zeit. Von daher sollte die Zeit von FHEM kommen.

Man könnte dazu ein FHEM-Device+Reading (oder dessen Timestamp) für die Zeit angeben und das als Zeit darstelln
.
Im einfachsten Fall könnte das device ein at sein, das alle Minute einfach nichts macht!

```
defmod atFHEMAppTime at +*00:01:00 {}
attr atFHEMAppTime alignTime 00:00
```

Von diesem at kann dann der Timestamp von state als Zeit genommen werden in der Art:

`atFHEMAppTime-state-ts:%d(time)`

**Comment by jemu75** [comment]
wird mit **v4.1.4** umgesetzt

**Comment by jemu75** [comment]
gelöst mit v4.1.4
