### ISSUE TITLE
Filterung der Panels fehlerhaft

### ISSUE THREAD

**Issue by binford6000** [jemu75/fhemApp#78]
Beim Filtern der Panels ist mir folgendes aufgefallen:
Ich habe zwei Panles welche mit 'panel' beginnen. Auf diese wird aber nicht gefiltert:

<img width="576" alt="image" src="https://github.com/jemu75/fhemApp/assets/29679540/e1c09a52-36e9-45d4-a896-f690be0d5b1f">

Erst wenn ich auf 'panel_' filtere, werden nur noch die beiden Panels angezeigt:

<img width="578" alt="image" src="https://github.com/jemu75/fhemApp/assets/29679540/758f6964-0620-4f41-b34d-a38f34d8f545">

**Comment by jemu75** [comment]
Hallo Sebastian,

ich kann den Fehler leider nicht reproduzieren. Kannst du mir bitte mal deine Konfiguration (siehe auch Tipp bzgl. "Anzeige der Internals") zukommen lassen, damit ich den Fehler eingrenzen kann.

Danke Dir
Jens

**Comment by binford6000** [comment]
> Kannst du mir bitte mal deine Konfiguration (siehe auch Tipp bzgl. "Anzeige der Internals") zukommen lassen, damit ich den Fehler eingrenzen kann.

Hilf mir bitte noch mal auf die Sprünge wo ich das finde...

**Comment by jemu75** [comment]
Dafür kannst du entweder in der URL das loglevel=7 setzen und dann in der Kopfzeile der App (oben rechts) auf das _i_ klicken.

Oder du gibst in der URL direkt den Pfad zu den Internals ein.
z.B.
`http://fhem:8083/fhem/fhemapp4/index.html#/myapp/internals`

**Comment by binford6000** [comment]
Ah OK danke. Hier meine [config.json](https://github.com/jemu75/fhemApp/files/14654548/config.json)

**Comment by jemu75** [comment]
Ich konnte das mit deiner Konfiguration nachstellen. Aktuell wird der Filter auf alle Spalten der Tabelle/Liste angewendet. Da in der Spalte _erweitert_ häufig das Wort **panel** steht, wird die Suche mit dem Suchbegriff nicht wirklich eingegrenzt. Auf welche Spalten sollte die Suche eingegrenzt werden?

![Bildschirmfoto vom 2024-03-19 19-23-09](https://github.com/jemu75/fhemApp/assets/80094691/3ced1aae-8921-4735-b551-c28ca7932925)

**Comment by binford6000** [comment]
Auf den Namen des Panels zu Filtern macht mMn. am meisten Sinn!

**Comment by jemu75** [comment]
Problem ist vuetify bereits bekannt -> [issue #18774](https://github.com/vuetifyjs/vuetify/issues/18774)

**Comment by jemu75** [comment]
Problem wird mit v4.1.3 behoben

**Comment by jemu75** [comment]
behoben mit v4.1.3
