### ISSUE TITLE
Vermeintlich korrekte Anzeige eines Panels obwohl die Ebene nicht vorhanden ist

### ISSUE THREAD

**Issue by binford6000** [jemu75/fhemApp#79]
Ich habe zwei Panels gefunden welche in der Vorschau korrekt angezeigt werden aber 'ohne Inhalt' sind.

![SCR-20240320-f71](https://github.com/jemu75/fhemApp/assets/29679540/7c690688-be4e-4004-8995-9e8a1c4fc9e5)

Das dazugehörige json unter Raw sieht so aus:
`{
	"name": "NAS",
	"template": "switch",
	"panel": {
		"navigation": [
			"system",
			"rooms->büro"
		],
		"devices": [
			"switch:nas.wol"
		],
		"sortby": [
			"4"
		]
	},
	"status": {
		"title": [
			"::NAS"
		]
	},
	"main": [
		{
			"level": {}
		}
	],
	"info": {
		"left1": [
			":::mdi-server"
		]
	}
}`

**Comment by jemu75** [comment]
Die Definition `... "main": [ { "level": {} } ], ...` beinhaltet nichts. Kannst du bitte beschreiben, was genau mit der Panel-Definition bezweckt werden soll.

**Comment by jemu75** [comment]
In der raw-Definition wird `"main": [ { "level": {} } ]` lediglich als "Platzhalter" angezeigt. Aber wie du im UI-Mode sehen kannst, gibt es in dem Panel keine geänderte Definition für die Ebene(n). Deshalb ist die Vorschau auch korrekt, da die Ebene aus dem Template kommt.
