### ISSUE TITLE
DCOM Exception bei %n Ersetzungen mit anschließendem €-Zeichen

### ISSUE THREAD

**Issue by binford6000** [jemu75/fhemApp#80]
Wenn info-text3 wie folgt definiert `fuel-min_diesel_value:: %n(2)°C:text-left` wird die Einheit korrekt angezeigt.

![image](https://github.com/jemu75/fhemApp/assets/29679540/7112c032-c4d0-4e86-a712-a86e90b1cd02)

Mit einem '€'-Zeichen `fuel-min_diesel_value:: %n(2)€:text-left` dagegen nicht und man kann auch nicht abspeichern:

![image](https://github.com/jemu75/fhemApp/assets/29679540/a238d866-7688-492c-99a5-091c1f24b421)

Die Konsole offenbart dass das €-Zeichen nicht im Zeichensatz enthalten ist:
`DOMException: Failed to execute 'btoa' on 'Window': The string to be encoded contains characters outside of the Latin1 range. 
`

**Comment by binford6000** [comment]
Ein Escapen des '€' mit `\€` funktioniert übrigens auch nicht.

**Comment by jemu75** [comment]
Wird mit **v4.0.30-beta** behoben.
