### ISSUE TITLE
Encoding-"Problem"?

### ISSUE THREAD

**Issue by benni1972** [jemu75/fhemApp#81]
Hallo Jens,

anscheinend haben wir irgendwie ein Encoding-Problem.

Siehe dazu auch folgenden Forums-Post von Jürgen (juemuc): https://forum.fhem.de/index.php?topic=137239.msg1307866#msg1307866

Es ist grundsätzlich erst mal nur ein Darstellungs-Problem und kein funktionales, von daher hat das definitiv keine Prio!

Das Verhalten kann ich auf meinen beiden Systemen nachvollziehen. 
Es ist dabei egal, ob ich "set getConfig", "get rawConfig" oder über Edit-Files gehe. Selbst beim editieren des Config-Files direkt im Dateisystem ist die Darstellung, wie im Post angegeben.

So weit ich das analysieren konnte, sind die Daten, die ich von dir bekomme anscheinend in cp1252 (Windows 1252), zumindest erkennt das VSCode beim Öffnen der Config-Datei und kann entsprechend wandeln, dass die Sonderzeichen (hier Umlaute) korrekt dargestellt werden.

Da wir die Daten ja base64-codiert austauschen, bleibt eigentlch nur die Möglichkeit, dass die Daten schon so von dir kommen. 
Denn ich nehme die nur, mache ein base64_decode (das kümmert sich nicht um irgendwelche encodings) und spreichere das Eergebnis einmal im Hash des device und in der Config-Datei.

Kannst es dir bei Gelegenheit ja mal anschauen, vielleicht findest du auf FHEMApp-Seite etwas.

Kategorie: minor, glitch

**Comment by jemu75** [comment]
Mit v4.0.35-beta gelöst
