### ISSUE TITLE
Bei Templates MIT 'imageURL' und OHNE 'title' werden die Ebenen-Pfeile nicht angezeigt

### ISSUE THREAD

**Issue by binford6000** [jemu75/fhemApp#83]
Gegeben ist ein Template mit mehreren Ebenen, einer imageURL und KEINEM title (der title ergibt sich aus der imageURL, siehe Bilder). Bleibt nun der title komplett leer, werden die Pfeile zum Durchschalten der Ebenen nicht angezeigt:

![SCR-20240327-jb5](https://github.com/jemu75/fhemApp/assets/29679540/665db505-3a3a-4142-bc5b-ec1c2d39ddf5)

Wird als Title zumindest EIN ZEICHEN (Blank funktioniert erwartungsgemäß nicht) eingegeben, werden die Ebenen-Pfeile wieder angezeigt:

![SCR-20240327-jbp](https://github.com/jemu75/fhemApp/assets/29679540/3c07cdbb-6ae6-471e-a227-a5e40c6a6fc0)

**Comment by binford6000** [comment]
Hier noch das betroffene Template [fhemapp.json](https://github.com/jemu75/fhemApp/files/14774045/fhemapp.json)

**Comment by jemu75** [comment]
wird mit **v4.0.33-beta** behoben.
