### ISSUE TITLE
Eigenständige Readings für room und group

### ISSUE THREAD

**Issue by hawkeyexp** [jemu75/fhemApp#86]
Erst mal Feedback: die GUI geht absolut in die richtige Richtung - weiter so!

Soweit ich das aktuell sehe wird nur room und group gelesen - selbst wenn ich ein eigenes Template mache, wird ein alternatives Reading nicht gelesen auch wenn es im Template angesprochen wird.

Das macht die Sorütierung hier und da unschön: Beispiel: Temperaturtrend mittels Chart - hier wird das Logfile ausgelesen also room/group von diesem Device - Logs sind bei mir aber in einer Untergruppe in Fhem da sie mich nicht wirklich interessieren - nur das SVG dazu welches dann im passenden Raum ist.

Hier eine Idee: alternative readings definierbar welches dann als room bzw. group verwendet werden - ein zusätzliches reading in Fhem wäre dann auch nicht zwigend da man dann z.B. alexaRoom etc. "missbrauchen" könnte die ggf. eh schon da sind oder doch eigenständige wenn man es ganz sauber trennen will :-)

**Comment by benni1972** [comment]
Hallo hawkeyexp,

dafür muss man doch FHEMApp-seitig eigentlich gar nichts machen!

Zunächst mal zur Begrifflichkeit: room und group sind in FHEM Attribute und keine Readings

Man kann sich nun einfach über das global-Device zusätzliche Attribute per userattr (bspw. fhemappRoom und fhemappGroup) definieren, die stehen dann, wenn am global device definiert für alle devices in FHEM zur Verfügung. 

Die kann man nun auch direkt in FHEMApp für Räume und Gruppen verwenden.

Ich habe das bei mir so gelöst, dass ich das zu Verwendenden Attribut in fhemapp, je nach Vorhandensein in FHEM verwende, also gibt es ein attribut fhemappRoom (a-fhemappRoom=.+) dann verwende das, ansonsten nächste Prüfung: gibt es ein Attribut room (a-room=.+), wenn nicht, dann verwende einen String aus FHEMAPP (Sprachen) %t(...)

Das mache ich bei mir übrigens schon lange so.
Das mit der bedingten Verwendung von Atrtibuten funktioniert natürlich auch mit Readings oder internals

Btw.: Es wäre besser gewesen, das erst mal als Frage im Forum zu stellen ("gibt's da schon was?")

Gruß Benni

**Comment by jemu75** [comment]
Hallo hawkeyexp,

ergänzend zu dem, was Benni geschrieben hat folgender Tipp. Du musst in FHEMApp die Elemente nicht zwingend mit Readings oder Attributen aus FHEM verbinden.
Du kannst in der Template bzw. Panelkonfiguration unter Navigation auch folgendes definieren:
`::Home` -> zeigt dein Panel in FHEMApp unter Home an
`::Gruppen->Charts` -> zeigt dein Panel in FHEMApp unter Gruppen und hier unter Charts an
`::Gruppen->Charts,Home` -> zeigt dein Panel in FHEMApp unter Gruppen und hier unter Charts an sowie unter Home an

Damit bist du völlig unabhängig von deiner Struktur innerhalb von FHEM. Schau gern auch mal in die Doku. Dort ist zum Thema Navigation auch nochmal alles wichtige beschrieben. 

Ansonsten, wie Benni schon geschrieben hat, gern mal im Forum weitere Fragen stellen. Dort gibt es auch viele erfahrene User, die gern helfen. 

Beste Grüße 
Jens
