### ISSUE TITLE
Menu wiederholt gleiche Einträge nach Auswahl [V4.1.0]

### ISSUE THREAD

**Issue by binford6000** [jemu75/fhemApp#89]
Gegeben ist ein Panel welches für [Licht,Rollläden,...] das Debuglevel [0,1,2] festlegt. Jedes Menü enthält dabei die gleichen Werte und jede Ebene das gleiche Menü. Wählt man nun einen Menüeintrag aus, so wird bei der nächsten Auswahl das Menü doppelt angezeigt usw:
 
![Bildschirmaufnahme 2024-04-29 um 08 10 43](https://github.com/jemu75/fhemApp/assets/29679540/cf955298-09ab-4ea6-84a5-f4a2e8e8a72a)

Ein Aktualisieren der Seite via Browser-Reload oder Menü->Aktualisieren setzt die Menüs wieder auf 1x Darstellung zurück.

**Comment by binford6000** [comment]
Hier die Definition von den Debuglevels:
[debuglevels.json](https://github.com/jemu75/fhemApp/files/15152889/debuglevels.json)

**Comment by jemu75** [comment]
Fehler bestätigt. Wird mit v4.1.1 behoben

**Comment by jemu75** [comment]
folgende Hinweise noch (unabhängig von dem Fehler)

1. das "switch-i-STATE" kannst du weglassen
```
"imageUrl": [
			"switch-i-STATE::http\\://10.3.3.6\\:8083/fhem/fhemapp_images/caution.png"
		],
```
2. das letzte "set-Kommando" (unterste Ebene) sieht merkwürdig aus
```
				"menu": [
					"dev-state::0:set dev cal 0",
					"dev-state::1:set dev cal 1",
					"dev-state::02set dev cal 2"
				]
```

**Comment by jemu75** [comment]
gelöst mit v4.1.1
