### ISSUE TITLE
Sprung zum Device im FHEM-Backend

### ISSUE THREAD

**Issue by benni1972** [jemu75/fhemApp#90]
In FHEMApp3.x gab es die Möglichkeit aus FHEMApp heraus direkt in das entsprechende FHEM-Device im FHEM-Backend zu springen. Das war auch nur bei erhöhtem loglevel möglich.

Das vermisse ich ab und zu :)

Ich weiß, dass es durch die Device-Keys inzwischen mehrere Devices-Gibt, zu denen man springen könnte. Von daher wird es ein einfacher zusätzlicher Button (in loglevel 7) nicht tun. Und noch ein Button mehr macht's auch nicht schöner.

Hier würde es wahrscheinlich schon Sinn machen, den Absprung direkt bei der Device-Zuordnung in der jeweiligen Panel-Konfig einzubauen.

Wie meistens:  nice to have ;)

Gruß Benni

**Comment by jemu75** [comment]
Hallo Benni,

folgender Vorschlag. Damit man in loglevel 7 auf alle relevanten Punkte eingehen kann, könnte ich statt der unterschiedlichen Buttons ein Ootionsmenü oben rechts ins Panel einbauen. Dort könnte ich die entsprechende "Sprünge" (Panelkonfiguration, Templatekonfiguration, Sprung zu FHEM Devices) ermöglichen.
Was meinst du zu dem Vorschlag?

Grüße
Jens

**Comment by jemu75** [comment]
gelöst mit v4.1.1

**Comment by benni1972** [comment]
Mensch Jens,

du bist ja fix! 

Ich habe mir das mit dem Optionsmenü gerade noch schnell angeschaut und muss sagen, das war eine prima Idee!
Ich mag es jetzt schon :)

VG Benni.
