### ISSUE TITLE
Vorlage in der Panel-Liste

### ISSUE THREAD

**Issue by benni1972** [jemu75/fhemApp#91]
Es wäre praktisch, wenn in der Panels-Auflistung auch eine (filterbare) Spalte mit dem jeweils zugeordneten Template enthalten wäre.
Optional natürlich gerne mit dem Sprung ins jeweilige Template.

Umgekehrt wäre es dann noch super-nice, wenn man von der Vorlage in die entsprechend, nach Template gefilterte Liste der Panels springen könnte.

Kategorie: nice to have

Gruß Benni

**Comment by jemu75** [comment]
Hallo Benni,

kann es sein, dass Du bei der Beschreibung der Anforderung Template und Panel vertauscht hast? Oder habe ich die Anforderung nicht verstanden? ;-) 

Grüße
Jens

**Comment by benni1972** [comment]
Hallo Jens,

ja, tatsächlich habe ich irgendwie, die Begriffe durcheinander gebracht, sorry!
Der Wunsch ist tatsächlich, das in der Liste der Panels direkt ersichtlich ist, welche Vorlage zugeordnet ist. 

Gruß Benni

**Comment by jemu75** [comment]
umgesetzt mit v4.1.3
