### ISSUE TITLE
Der Zurück-Button bei den Panels und bei den Vorlagen funktioniert nicht mehr

### ISSUE THREAD

**Issue by benni1972** [jemu75/fhemApp#93]
Hallo Jens,

wie im Betreff geschrieben funktioniert der Back-Button nicht mehr.

Wenn ich ein Panel oder eine Vorlage zur Bearbeitung öffne, kann ich anschließend mit dem Button nicht wieder in die jeweilige Panel- oder Vorlagenliste zurückkehren.

In der Console sind keine Auffälligkeiten sichtbar, auch nicht unter loglevel 7

Gruß Benni

**Comment by jemu75** [comment]
wird mit v4.1.2 behoben

**Comment by jemu75** [comment]
behoben mit v4.1.2
