### ISSUE TITLE
Klick in der Navigationsleiste öffnet alle gleichnamigen Navigations-Punkte

### ISSUE THREAD

**Issue by benni1972** [jemu75/fhemApp#94]
Hallo Jens,

ich habe für meine Navigations-Leiste u.a. einen Navigationspunkt rooms (Räume) und einen Navigationspunkt FHEM (fhem) definiert.
In FHEMApp4 weiße ich meine Panels dem Navigations-Punkt rooms zu, also bspw.: rooms->EG->Wohnen.

Das mache ich über ein Attribtut faRoom aus FHEM und die Zuweisung ist in allen meinen Vorlagen enthalten (<deviceKey>-a-faRoom:.+:rooms->%s) im Attribut in FHEM steht dann eben nur noch drin "EG->Wohnen"

Weiterhin habe ich in allen meinen Vorlagen definiert, das die komplette Raumstruktur aus FHEM unter dem Navigationspunkt fhem ebenfalls zu finden sein soll. Definiert in den Vorlagen unter Navigation: <deviceKey>-a-room:.+:fhem->%s

Soweit funktioniert das auch. Allerdings gibt es nun sowohl unter rooms, als auch unter fhem gleichnamige Räume (bspw. EG oder Flur ...) Wenn ich nun einen solchen per Klick öffne (bspw. unter rooms), wird auch der andere, gleichnamige (unter fhem) geöffnet. Das stört, weil dabei die Navigationsleiste auch springt.

Wahrscheinlich hat das v.a. mit der Gleichnamigkeit zu tun und nichts mit meiner Vorlagendefinition.

Im Anhang auch 2 Screenshots, die das Verhalten zeigen.

Gruß Benni 

<img width="260" alt="Bildschirm­foto 2024-05-01 um 13 12 45" src="https://github.com/jemu75/fhemApp/assets/82200777/ca2aef73-7e63-43ea-98eb-8c9756e1a9cd">

<img width="168" alt="Bildschirm­foto 2024-05-01 um 13 13 19" src="https://github.com/jemu75/fhemApp/assets/82200777/94c08841-52ce-48c9-b073-f2e7dec70509">

**Comment by jemu75** [comment]
Fehler bestätigt. Wird mit v4.1.3 behoben

**Comment by jemu75** [comment]
behoben mit v4.1.3
