### ISSUE TITLE
LongClick und LongReleas in der mobilen Ansicht funktionieren nicht (mehr)

### ISSUE THREAD

**Issue by benni1972** [jemu75/fhemApp#95]
Hallo Jens,

wie im Betreff schon geschrieben funktioniert bei Buttons der LongClick, bzw. der LongRelease nicht mehr in der mobilen Ansicht.
Das ist sowohl im realen Leben, also auf dem Handy so, als auch, wenn ich im Browser am Rechner in den Entwickler-Tools auf mobile Ansicht wechsle.

Ich bin mir sicher, dass das schon funktioniert hat, denn für das Panel zur Steuerung meines Garagentors, habe ich zur Sicherheit nur LongClick verwendet, um ein versehentliches Öffnen zu verhindern und das nutze ich relativ häufig.

Gruß Benni

**Comment by jemu75** [comment]
Fehler bestätigt. Wird mit v4.1.2 behoben

**Comment by jemu75** [comment]
behoben mit v4.1.2
