### ISSUE TITLE
Cursortasten bei der RAW-Bearbeitung von Vorlagen fehlerhaft

### ISSUE THREAD

**Issue by Himbi777** [jemu75/fhemApp#97]
Hallo Jens

erstmal großes Lob an deine neue Version 4.x und den Enthusiasmus, den du in die Programmierung steckst. 
Ich bin mittlerweile auch dabei meine Installation auf die neue Version hochzuheben.
Bei der Übernahme der alten Templates auf die Panel in V4 ist mir ein Fehler in der RAW-Bearbeitung der Vorlagen aufgefallen:

Um im Text zu navigieren, funktionieren die Cursor-Tasten LINKS und RECHTS so wie erwartet. Die AUF un AB Tasten steuern allerdings nicht den Cursor sondern springen im Browserfenster das nächste Fensterelement an.
Getestet mit Chrome und Firefox.

Gruß Gerhard

**Comment by benni1972** [comment]
Kann ich bestätigen! Ist auch bei mir auf dem Mac im Chrome so!

**Comment by jemu75** [comment]
behoben mit v4.1.3
