### ISSUE TITLE
Sortiermöglichkeit der Räume und Gruppen 

### ISSUE THREAD

**Issue by Himbi777** [jemu75/fhemApp#98]
Hallo Jens
In der Version 3 waren die Räume und Gruppen alphabetisch sortiert. In der neuen Version 4 habe ich den entsprechenden Punkt zur Sortierung noch nicht gefunden.

Kannst du mir bitte auf die Sprünge helfen?
Danke und Gruß 
Gerhard

**Comment by jemu75** [comment]
Hallo Gerhard,

die Navigation wird alphabetisch sortiert, wenn die Werte z.B. Räume oder Gruppen als Reading aus FHEM übernommen oder direkt im Panel bzw. im Template festgelegt werden. Wenn Du zusätzlich die Navigationselemente in den Einstellungen (unter dem Tab Navigation) konfigurierst, dann wird die Reihenfolge dieser Elemente übernommen.
Eine schnelle Sortierung innerhalb der Navigationseinstellungen ist aktuell noch nicht umgesetzt. 

Ich hoffe das hilft Dir für den Moment weiter. Melde Dich gern bei weiteren Fragen. 🙂

Grüße
Jens

**Comment by Himbi777** [comment]
Hallo Jens
ich habe die Readings aus  FHEM übernommen, mit der Vorlage aus einem Standard Template:
**light-a-room::Räume->%s**
Wenn ich dies in der Vorlage lösche, sind die entsprechenden Geräte gar nicht mehr sichtbar.

Gruß Gerhard

![Screenshot_20240503-210114_Chrome~2](https://github.com/jemu75/fhemApp/assets/59026971/1dcb6a58-7060-4dca-aa39-d88545af562c)

**Comment by jemu75** [comment]
Hallo Gerhard,

in der Panel- bzw. Template-Definition muss mindestens eine Definition hinterlegt werden, die angibt, unter welchem Navigationspunkt das Panel angezeigt werden soll.

Die Definition kann statisch oder dynamisch oder gemischt erfolgen. Beispiel:

`::Home` es wird ein Punkt **Home** im Navigationsmenü erzeugt und das Panel unter diesem Menüpunkt angezeigt

`device-a-room::%s` es wird für den Wert, der im FHEM Attribute room hinterlegt ist, ein Punkt im Navigationsmenü erzeugt und das Panel unter diesem Menüpunkt angezeigt

`device-a-room::Räume->%s` es wird für den Wert, der im FHEM Attribute room hinterlegt ist, ein Unterpunkt unter **Räume** im Navigationsmenü erzeugt und das Panel unter diesem Menüpunkt amgezeigt

Soweit zu den Panel- bzw. Template-Definitionen.

Nun gibt es in den Einstellungen zusätzlich (optional) die Möglichkeit, die erzeugten Navigationspunkte anzupassen. Also z.B. zusätzlich mit einem Icon zu versehen, oder einen separaten Titel anzuzeigen bzw. ein Menü für unterschiedliche Sprachen zu erzeugen oder eben die Sortierung der erzeugten Menüeinträge manuell zu übersteuern, wenn diese nicht in alphabetischer Reihenfolge angezeigt werden sollen. Für den Beginn kannst du den Tab **Navigation** in den Einstellungen erstmal leer lassen. Wichtig ist aber, dass du deinen Panels mindestens einen Navigationspunkt mitgibst, unter dem sie angezeigt werden sollen.

Grüße
Jens

**Comment by Himbi777** [comment]
Hi Jens,
ich hab es jetzt endlich geschnallt😊
Ich muss in der Navigation für die Bereiche und Gruppen einmal eine Verknüpfung anlegen,dort kann man dann auch die Unterpunkte sortieren lassen. 
Es ergibt sich dann die gleiche Anzeige wie in der V3.  PERFEKT!!

Gruß Gerhard
![Screenshot_20240504-132745_Chrome~2](https://github.com/jemu75/fhemApp/assets/59026971/de6a9452-93d9-4b4d-91ac-dfcceddb89f6)
