### ISSUE TITLE
Default-Route für den Root-Link

### ISSUE THREAD

**Issue by benni1972** [jemu75/fhemApp#99]
Hallo Jens, 

Wenn ich im Browser meine FHEMApp4-Instanz mit der "Root"-Route aufrufe, wird eine leere Seite angezeigt

(Beispielaufruf: https://myfhemhost/fhem/fa2ui/index.html#/fa2/)

Wenn ich zuvor bereits auf einer anderen FHEMApp4-Seite war (bspw.: https://myfhemhost/fhem/fa2ui/index.html#/fa2/devices/home) dann bleibt er bei erneuter eingabe der Root-Route auf der Home-Seite.

Cool wäre es jetzt, wenn man, ähnlich wie beim FHEMWEB-Device in den Einstellungen einen defaultRoom (oder hier eine default-Route, wie eben "/devices/home", kann gerne auch ein Auswahlwert aus "Navigations" sein) einstellen könnte auf denn er dann Springt.

Gruß Benni

**Comment by jemu75** [comment]
Guter Vorschlag. Wird mit v4.1.3 umgesetzt :-)

**Comment by benni1972** [comment]
Cool! Danke! ;)

**Comment by jemu75** [comment]
umgesetzt mit v4.1.3
